package sistemasolicitudes;

import java.awt.HeadlessException;
import java.awt.event.KeyEvent;
import java.sql.ResultSet;
import java.sql.SQLException;
import javax.swing.JOptionPane;


public class dialogImpuestoSucesorio extends javax.swing.JDialog {

    int cod,idsol, yearIntro, yearInicio, yearFinal;
    String tipEscr, seguido, causante, lugar, year1, otros, mes,dia,num_solicitud,ver_solicitud,NumIdSol;
    conexion con = new conexion();
    private final ReportImpuestoSucesorio jasper;
    
    /** Creates new form EscriturasPublicas
     * @param parent
     * @param modal */
    public dialogImpuestoSucesorio(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        
        jasper= new ReportImpuestoSucesorio();
        
        //Ocultado controles de la ventana
        jLabel5.setVisible(false);
        lblCod.setVisible(false);
        lblIdSol.setVisible(true);
        btnChangeDat.setVisible(false);
        
        desactiva();
        
        
    }
    
    public void desactiva(){
        this.txtSolicitud.setText("");
        this.txtSolicitud.setEditable(false);
        this.txtNumDoc.setEditable(false);
        this.txtNom.setEditable(false);
        this.txtcausante.setEditable(false);
        this.txtNom.setEditable(false);
        this.txtNumDoc.setEditable(false);
        this.txtseguido.setEditable(false);
        this.txtOtros.setEditable(false);
        this.txtDia.setEditable(false);
        this.cboxMes.setSelectedIndex(0);
        this.txtAño.setEditable(false);
        this.txtlugar.setEditable(false);
        this.btnGuardar.setEnabled(false);
        this.btnImprimir.setEnabled(false);
        this.btnUsu.setEnabled(false);
    }
    
    public void activa(){
        this.txtNumDoc.setEditable(true);
        this.txtNom.setEditable(true);
        this.txtcausante.setEditable(true);
        this.txtNom.setEditable(true);
        this.txtNumDoc.setEditable(true);
        this.txtseguido.setEditable(true);
        this.txtOtros.setEditable(true);
        this.txtDia.setEditable(true);
        this.cboxMes.setSelectedIndex(0);
        this.txtAño.setEditable(true);
        this.txtlugar.setEditable(true);
        this.btnGuardar.setEnabled(true);
        this.btnUsu.setEnabled(true);
    }
    
    public void limpiar(){
        txtcausante.setText("");
        txtNom.setText("");
        txtNumDoc.setText("");
        txtseguido.setText("");
        txtOtros.setText("");
        txtDia.setText("");
        cboxMes.setSelectedIndex(0);
        txtAño.setText("");
        txtlugar.setText("");
        this.btnImprimir.setEnabled(false);
        desactiva();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel15 = new javax.swing.JLabel();
        txtcausante = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        txtseguido = new javax.swing.JTextField();
        txtDia = new javax.swing.JTextField();
        jLabel20 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        txtAño = new javax.swing.JTextField();
        jLabel19 = new javax.swing.JLabel();
        cboxMes = new javax.swing.JComboBox();
        jLabel11 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtOtros = new javax.swing.JTextArea();
        jLabel2 = new javax.swing.JLabel();
        txtlugar = new javax.swing.JTextField();
        btnGuardar = new javax.swing.JButton();
        btnImprimir = new javax.swing.JButton();
        btnNuevo = new javax.swing.JButton();
        txtSolicitud = new javax.swing.JTextField();
        jLabel23 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        txtNumDoc = new javax.swing.JTextField();
        txtNom = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        lblCod = new javax.swing.JLabel();
        btnUsu = new javax.swing.JButton();
        btnCancelar = new javax.swing.JButton();
        btnVer = new javax.swing.JButton();
        btnChangeDat = new javax.swing.JButton();
        labelIdSol = new javax.swing.JLabel();
        lblIdSol = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 22)); // NOI18N
        jLabel1.setText("Impuesto Sucesorio");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 40, -1, -1));

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)), "Datos del documento", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 12))); // NOI18N
        jPanel2.setLayout(null);

        jLabel15.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel15.setText("Causante:");
        jPanel2.add(jLabel15);
        jLabel15.setBounds(60, 80, 60, 15);

        txtcausante.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txtcausante.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtcausanteKeyPressed(evt);
            }
        });
        jPanel2.add(txtcausante);
        txtcausante.setBounds(130, 80, 410, 30);

        jLabel14.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel14.setText("Seguido por:");
        jPanel2.add(jLabel14);
        jLabel14.setBounds(40, 50, 80, 15);

        txtseguido.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txtseguido.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtseguidoKeyPressed(evt);
            }
        });
        jPanel2.add(txtseguido);
        txtseguido.setBounds(130, 43, 410, 30);

        txtDia.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txtDia.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtDiaKeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtDiaKeyTyped(evt);
            }
        });
        jPanel2.add(txtDia);
        txtDia.setBounds(150, 160, 42, 30);

        jLabel20.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel20.setText("Año");
        jPanel2.add(jLabel20);
        jLabel20.setBounds(350, 160, 22, 15);

        jLabel18.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel18.setText("Dia");
        jPanel2.add(jLabel18);
        jLabel18.setBounds(130, 160, 16, 15);

        txtAño.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txtAño.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtAñoKeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtAñoKeyTyped(evt);
            }
        });
        jPanel2.add(txtAño);
        txtAño.setBounds(380, 160, 50, 30);

        jLabel19.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel19.setText("Mes");
        jPanel2.add(jLabel19);
        jLabel19.setBounds(200, 160, 21, 15);

        cboxMes.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        cboxMes.setModel(new javax.swing.DefaultComboBoxModel(new String[] { " ", "ENERO", "FEBRERO", "MARZO", "ABRIL", "MAYO", "JUNIO", "JULIO", "AGOSTO", "SETIEMBRE", "OCTUBRE", "NOVIEMBRE", "DICIEMBRE" }));
        cboxMes.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                cboxMesKeyPressed(evt);
            }
        });
        jPanel2.add(cboxMes);
        cboxMes.setBounds(230, 160, 104, 30);

        jLabel11.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel11.setText("Mas datos:");
        jPanel2.add(jLabel11);
        jLabel11.setBounds(550, 110, 58, 15);

        jScrollPane1.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_ALWAYS);

        txtOtros.setColumns(20);
        txtOtros.setRows(5);
        jScrollPane1.setViewportView(txtOtros);

        jPanel2.add(jScrollPane1);
        jScrollPane1.setBounds(550, 130, 302, 60);

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel2.setText("Lugar:");
        jPanel2.add(jLabel2);
        jLabel2.setBounds(80, 120, 34, 15);

        txtlugar.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtlugarKeyPressed(evt);
            }
        });
        jPanel2.add(txtlugar);
        txtlugar.setBounds(130, 120, 230, 30);

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 160, 870, 220));

        btnGuardar.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btnGuardar.setText("Guardar");
        btnGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGuardarActionPerformed(evt);
            }
        });
        getContentPane().add(btnGuardar, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 410, 130, 40));

        btnImprimir.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btnImprimir.setText("Imprimir");
        btnImprimir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnImprimirActionPerformed(evt);
            }
        });
        getContentPane().add(btnImprimir, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 410, 130, 40));

        btnNuevo.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        btnNuevo.setText("Nuevo");
        btnNuevo.setBorder(null);
        btnNuevo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNuevoActionPerformed(evt);
            }
        });
        getContentPane().add(btnNuevo, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 90, 170, 60));

        txtSolicitud.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txtSolicitud.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtSolicitudActionPerformed(evt);
            }
        });
        getContentPane().add(txtSolicitud, new org.netbeans.lib.awtextra.AbsoluteConstraints(599, 50, 100, 30));

        jLabel23.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel23.setText("Solicitud N°:");
        getContentPane().add(jLabel23, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 60, -1, -1));

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel4.setText("N° Documento:");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 100, -1, -1));

        txtNumDoc.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txtNumDoc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNumDocActionPerformed(evt);
            }
        });
        txtNumDoc.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtNumDocKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtNumDocKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtNumDocKeyTyped(evt);
            }
        });
        getContentPane().add(txtNumDoc, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 100, 179, -1));

        txtNom.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txtNom.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtNomKeyPressed(evt);
            }
        });
        getContentPane().add(txtNom, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 130, 400, -1));

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel3.setText("Nombre:");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 130, -1, -1));

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel5.setText("Codigo Usuario:");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 10, -1, -1));

        lblCod.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        lblCod.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        getContentPane().add(lblCod, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 10, 81, 18));

        btnUsu.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        btnUsu.setText("BUSCAR SOLICITANTE");
        btnUsu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUsuActionPerformed(evt);
            }
        });
        getContentPane().add(btnUsu, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 100, -1, -1));

        btnCancelar.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btnCancelar.setText("Cancelar");
        btnCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelarActionPerformed(evt);
            }
        });
        getContentPane().add(btnCancelar, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 410, 130, 40));

        btnVer.setText("Visualizar Solicitud");
        btnVer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVerActionPerformed(evt);
            }
        });
        getContentPane().add(btnVer, new org.netbeans.lib.awtextra.AbsoluteConstraints(740, 100, 150, -1));

        btnChangeDat.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btnChangeDat.setText("Cambiar Datos");
        btnChangeDat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnChangeDatActionPerformed(evt);
            }
        });
        getContentPane().add(btnChangeDat, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 410, 180, 40));

        labelIdSol.setText("labelIdSol");
        getContentPane().add(labelIdSol, new org.netbeans.lib.awtextra.AbsoluteConstraints(880, 490, 80, -1));

        lblIdSol.setText("lblIdSol");
        getContentPane().add(lblIdSol, new org.netbeans.lib.awtextra.AbsoluteConstraints(740, 10, 126, -1));

        jButton1.setText("ReImprimir Solicitud");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(740, 130, 150, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtcausanteKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtcausanteKeyPressed
        if(KeyEvent.VK_ENTER == evt.getKeyCode()){
            txtlugar.requestFocus();
        }
    }//GEN-LAST:event_txtcausanteKeyPressed

    private void txtseguidoKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtseguidoKeyPressed
        if(KeyEvent.VK_ENTER == evt.getKeyCode()){
            txtcausante.requestFocus();
        }
    }//GEN-LAST:event_txtseguidoKeyPressed

    private void txtDiaKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtDiaKeyPressed
        // TODO add your handling code here:
        if(KeyEvent.VK_ENTER == evt.getKeyCode()){
            cboxMes.requestFocus();
        }
        
    }//GEN-LAST:event_txtDiaKeyPressed

    private void txtDiaKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtDiaKeyTyped
        // TODO add your handling code here:
        int n = (int)evt.getKeyChar();
        if(n>=48 && n<=57 || n==13 || n==127){

        }else{
            evt.setKeyChar((char)KeyEvent.VK_CLEAR);
        }
    }//GEN-LAST:event_txtDiaKeyTyped

    private void txtAñoKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtAñoKeyPressed
        if(KeyEvent.VK_ENTER == evt.getKeyCode()){
            txtOtros.requestFocus();
        }
    }//GEN-LAST:event_txtAñoKeyPressed

    private void txtAñoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtAñoKeyTyped
        // TODO add your handling code here:
        int n = (int)evt.getKeyChar();
        if(n>=48 && n<=57 || n==13 || n==127){

        }else{
            evt.setKeyChar((char)KeyEvent.VK_CLEAR);
        }
    }//GEN-LAST:event_txtAñoKeyTyped

    private void cboxMesKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_cboxMesKeyPressed
        if(KeyEvent.VK_ENTER == evt.getKeyCode()){
            txtAño.requestFocus();
        }
    }//GEN-LAST:event_cboxMesKeyPressed

    private void btnGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuardarActionPerformed
        cod = Integer.parseInt(lblCod.getText());
        idsol =Integer.parseInt(lblIdSol.getText());
        int codTipSol=7;
        //
        num_solicitud = this.txtSolicitud.getText();
        seguido = this.txtseguido.getText().toUpperCase();
        causante = this.txtcausante.getText().toUpperCase();
        lugar = this.txtlugar.getText().toUpperCase();
        dia = this.txtDia.getText().toUpperCase();
        mes = this.cboxMes.getSelectedItem().toString();
        year1 = this.txtAño.getText();
        otros = this.txtOtros.getText().toUpperCase();

            try{
                int rpta = JOptionPane.showConfirmDialog(rootPane,"¿Estas Seguro de Guardar?","ARP Sistema",JOptionPane.YES_NO_OPTION);
                if(rpta == 0){
                    con.conectar();
                    con.insertar("INSERT INTO impuestosucesorio VALUES (null,'Impuesto Sucesorio','"+seguido+"','"+causante+"','"+lugar+"','"+dia+"','"+mes+"','"+year1+"','"+otros+"');");
                    con.insertar("INSERT INTO solicitudes(codSol,codUsu,codTipSol,idSol) VALUES ('"+num_solicitud+"','"+cod+"','"+codTipSol+"','"+idsol+"');");
                    this.btnImprimir.setEnabled(true);
                    this.btnGuardar.setEnabled(false);
                }else{
                    JOptionPane.showMessageDialog(rootPane, "Error guardando");

                    limpiar();
                }
            }catch(HeadlessException | SQLException e){
                JOptionPane.showMessageDialog(rootPane, "Error al Insertar los Registros en la Base de Datos" + e);
            }
        
    }//GEN-LAST:event_btnGuardarActionPerformed

    private void btnImprimirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnImprimirActionPerformed
        String num_sol = this.txtSolicitud.getText();
        jasper.ejecutarReporte(num_sol);
    }//GEN-LAST:event_btnImprimirActionPerformed

    private void btnNuevoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNuevoActionPerformed
        int solic=0,esc=0;
        try{
                con.conectar();
                ResultSet res=con.consulta("SELECT max(codSol) FROM solicitudes");
                res.next();
                solic=Integer.parseInt(res.getString(1));
                res=con.consulta("SELECT max(idSol) FROM impuestosucesorio ORDER BY idSol DESC LIMIT 1;");
                res.next();
                esc=Integer.parseInt(res.getString(1));
                con.cierraConexion();
            }catch(SQLException e){
                JOptionPane.showMessageDialog(rootPane, e);
            }
        txtSolicitud.setText(String.valueOf(solic+1));
        lblIdSol.setText(String.valueOf(esc+1));
        
        txtSolicitud.setText(String.valueOf(solic+1));
        lblIdSol.setText(String.valueOf(esc+1));
        txtcausante.setText("");
        txtNom.setText("");
        txtNumDoc.setText("");
        txtseguido.setText("");
        txtOtros.setText("");
        txtDia.setText("");
        cboxMes.setSelectedIndex(0);
        txtAño.setText("");
        txtlugar.setText("");
        txtNumDoc.requestFocus();
        activa();
    }//GEN-LAST:event_btnNuevoActionPerformed

    private void txtSolicitudActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtSolicitudActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtSolicitudActionPerformed

    private void txtNumDocActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNumDocActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNumDocActionPerformed

    private void txtNumDocKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtNumDocKeyPressed
        if(KeyEvent.VK_ENTER == evt.getKeyCode()){
            btnUsu.doClick();
        }
    }//GEN-LAST:event_txtNumDocKeyPressed

    private void txtNumDocKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtNumDocKeyReleased
        if(txtNumDoc.getText().length()>7){
            btnUsu.doClick();
        }
    }//GEN-LAST:event_txtNumDocKeyReleased

    private void txtNumDocKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtNumDocKeyTyped
        int n = (int)evt.getKeyChar();
        if(n>=48 && n<=57 || n==13 || n==127){

        }else{
            evt.setKeyChar((char)KeyEvent.VK_CLEAR);
        }
    }//GEN-LAST:event_txtNumDocKeyTyped

    private void txtNomKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtNomKeyPressed
        if(KeyEvent.VK_ENTER == evt.getKeyCode()){
            txtseguido.requestFocus();
        }
    }//GEN-LAST:event_txtNomKeyPressed

    private void btnUsuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUsuActionPerformed
        int numero = txtNumDoc.getText().length();
        String dni2 = "";

        if (numero <8){
            JOptionPane.showMessageDialog(rootPane, "Numero de Digitos de DNI Menor que 8 Numeros y de RUC es 11");
            this.txtNumDoc.requestFocus();
        }else{
            if (numero==8)
            {
                String dni=this.txtNumDoc.getText();
                try{
                    con.conectar();

                    ResultSet rs=con.consulta("SELECT codUsu,CONCAT(nombre,' ',apePat,' ',apeMat) AS nombre FROM usuarios WHERE numDoc='"+dni+"' LIMIT 0,1;");
                    rs.next();
                    this.txtNom.setText(rs.getString(2));
                    this.lblCod.setText(rs.getString(1));
                    con.cierraConexion();
                }catch(SQLException e){
                    JOptionPane.showMessageDialog(rootPane, "Usuario no encontrado","Administrador de Sistema",JOptionPane.INFORMATION_MESSAGE);
                    dni2 = this.txtNumDoc.getText();
                    dialogNuevoUsuario p=new dialogNuevoUsuario(null,true,dni2);
                    p.setVisible(true);
                }

            }else {if (numero==11){
                String ruc=this.txtNumDoc.getText();
                try{
                    con.conectar();
                    ResultSet rs=con.consulta("SELECT codUsu, apeMat from usuarios where numDoc='"+ruc+"' LIMIT 0,1;");
                    rs.next();
                    this.txtNom.setText(rs.getString(2));
                    this.lblCod.setText(rs.getString(1));
                    con.cierraConexion();
                }catch(SQLException e){
                    JOptionPane.showMessageDialog(rootPane, "Empresa no registrada","Administrador del Sitema", JOptionPane.INFORMATION_MESSAGE);
                    // = this.txtNunDNI.getText();
                    dialogNuevoJuridico p=new dialogNuevoJuridico(null, true, ruc);
                    p.setVisible(true);
                }
            }}
        }
    }//GEN-LAST:event_btnUsuActionPerformed

    private void btnCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarActionPerformed
        // TODO add your handling code here:
        desactiva();
        limpiar();
        this.btnChangeDat.setVisible(false);
        this.btnGuardar.setVisible(true);
    }//GEN-LAST:event_btnCancelarActionPerformed

    private void btnVerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVerActionPerformed
        // TODO add your handling code here:
        ver_solicitud = JOptionPane.showInputDialog("Ingrese Numero de Solicitud a visualizar");

        this.txtNumDoc.setEditable(true);
        this.btnUsu.setEnabled(true);
        this.txtcausante.setEditable(true);
        this.txtseguido.setEditable(true);
        this.txtOtros.setEditable(true);
        this.txtDia.setEditable(true);
        this.cboxMes.setSelectedIndex(0);
        this.txtAño.setEditable(true);
        this.txtlugar.setEditable(true);
        this.btnGuardar.setVisible(false);
        this.btnChangeDat.setVisible(true);
        
        try{
            con.conectar();
            ResultSet res = con.consulta("SELECT s.codSol,u.codUsu, CONCAT(u.nombre,' ',u.apePat,' ',u.apeMat)as usuario, u.codDis,u.numDoc, u.direccion,e.idSol,e.tipEsc,e.otorgante,e.favorecido, n.cod_not,CONCAT(n.nom_not,' ',n.pat_not,' ',n.mat_not) as notario, n.provincia, e.dia, e.mes, e.anio, e.obs FROM solicitudes AS s, usuarios AS u, escpublicas as e, notarios as n WHERE s.codUsu = u.codUsu  and s.idSol=e.idSol and e.codNot=n.cod_not and s.codSol = '"+ver_solicitud+"';");
            res.next();
            this.txtSolicitud.setText(res.getString("codSol"));
            this.txtNumDoc.setText(res.getString("numDoc"));
            this.lblCod.setText(res.getString("codUsu"));
            this.txtNom.setText(res.getString("usuario"));
            this.txtseguido.setText(res.getString("otorgante"));
            this.txtcausante.setText(res.getString("favorecido"));
            this.txtDia.setText(res.getString("dia"));
            this.cboxMes.setSelectedItem(res.getString("mes"));
            this.txtAño.setText(res.getString("anio"));
            this.txtOtros.setText(res.getString("obs"));
            this.labelIdSol.setText(res.getString("idSol"));
            con.cierraConexion();
        }catch(SQLException e){
            JOptionPane.showMessageDialog(rootPane, "Error Consultando. " + e);
        }
    }//GEN-LAST:event_btnVerActionPerformed

    private void btnChangeDatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnChangeDatActionPerformed
        // Activa los cuadros
        cod = Integer.parseInt(lblCod.getText());
        idsol =Integer.parseInt(lblIdSol.getText());
        // Recoje los datos
        
        NumIdSol = this.labelIdSol.getText();
        num_solicitud = this.txtSolicitud.getText();
        seguido = this.txtseguido.getText().toUpperCase();
        causante = txtcausante.getText().toUpperCase();
        dia = txtDia.getText().toUpperCase();
        mes = cboxMes.getSelectedItem().toString();

        year1 = this.txtAño.getText();
        otros = txtOtros.getText().toUpperCase();

        int rpta1 = JOptionPane.showConfirmDialog(rootPane,"¿Esta seguro de realizar estos cambios?","ARP Sistema",JOptionPane.YES_NO_OPTION);
        if(rpta1 == 0){
            try{
                con.conectar();
                con.actualizar("UPDATE impuestosucesorio SET seguido = '"+seguido+"',causante = '"+causante+"',lugar = '"+lugar+"',dia = '"+dia+"',mes = '"+mes+"',año = '"+year1+"',obs = '"+otros+"' WHERE idSol = '"+NumIdSol+"';");
                con.actualizar("UPDATE solicitudes SET codUsu = '"+cod+"', idSol = '"+NumIdSol+"' WHERE codSol = '"+num_solicitud+"';");
                JOptionPane.showMessageDialog(rootPane, "Datos Modificados Satisfactotiamente");
                //con.cierraConexion();
            }catch(Exception e){
                JOptionPane.showMessageDialog(rootPane, "Error Cambiando datos. " + e);
            }
        }
        this.btnChangeDat.setVisible(false);
        this.btnGuardar.setVisible(true);
        this.btnGuardar.setEnabled(false);
        this.btnImprimir.setEnabled(true);
    }//GEN-LAST:event_btnChangeDatActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        String solicitudD = JOptionPane.showInputDialog("Escriba el Numero de Solicitud");
        String num_sol = solicitudD;
        jasper.ejecutarReporte(num_sol);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void txtlugarKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtlugarKeyPressed
        if(KeyEvent.VK_ENTER == evt.getKeyCode()){
            txtDia.requestFocus();
        }
    }//GEN-LAST:event_txtlugarKeyPressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(dialogImpuestoSucesorio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(dialogImpuestoSucesorio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(dialogImpuestoSucesorio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(dialogImpuestoSucesorio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                dialogImpuestoSucesorio dialog = new dialogImpuestoSucesorio(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCancelar;
    private javax.swing.JButton btnChangeDat;
    private javax.swing.JButton btnGuardar;
    private javax.swing.JButton btnImprimir;
    private javax.swing.JButton btnNuevo;
    private javax.swing.JButton btnUsu;
    private javax.swing.JButton btnVer;
    private javax.swing.JComboBox cboxMes;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel labelIdSol;
    private javax.swing.JLabel lblCod;
    private javax.swing.JLabel lblIdSol;
    private javax.swing.JTextField txtAño;
    private javax.swing.JTextField txtDia;
    private javax.swing.JTextField txtNom;
    private javax.swing.JTextField txtNumDoc;
    private javax.swing.JTextArea txtOtros;
    private javax.swing.JTextField txtSolicitud;
    private javax.swing.JTextField txtcausante;
    private javax.swing.JTextField txtlugar;
    private javax.swing.JTextField txtseguido;
    // End of variables declaration//GEN-END:variables
}
