package sistemasolicitudes;

import java.awt.HeadlessException;
import java.awt.event.KeyEvent;
import java.sql.ResultSet;
import java.sql.SQLException;
import javax.swing.JOptionPane;

public class Enace extends javax.swing.JDialog {
    private static final long serialVersionUID = 1L;
    conexion con = new conexion();
    //Variables Globales
    int cod,idsol,not;
    String conPri, otor, favor, inst, lugar, año, otros, dia , mes, dni,ver_solicitud,NumIdSol,num_solicitud,codUsu;
    private ReporteEnace jasper;
    /** Creates new form Enace */

    /**
     * Creates new form Enace
     * @param parent
     * @param modal
     */
    public Enace(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        jasper=new ReporteEnace();

        txtSolicitud.setEditable(false);
        lblIdSol.setVisible(true);
        lblCod.setVisible(true);
        jLabel5.setVisible(false);
        labelIdSol.setVisible(false);
        btnChangeDat.setVisible(false);
        //
        int solic=0,esc=0;
        try{
                con.conectar();
                ResultSet res=con.consulta("SELECT max(codSol) FROM solicitudes");
                res.next();
                solic=Integer.parseInt(res.getString(1));
                res=con.consulta("SELECT idSol FROM enace ORDER BY idSol DESC LIMIT 1;");
                res.next();
                esc=Integer.parseInt(res.getString(1));
                con.cierraConexion();
            }catch(SQLException e){
                System.out.println(e);
            }
        txtSolicitud.setText(String.valueOf(solic+1));
        lblIdSol.setText(String.valueOf(esc+1));
    }
    public void desactiva(){
       this.txtSolicitud.setText("");
       this.txtSolicitud.setEditable(false);
       this.txtNumDoc.setEditable(false);
       this.txtNom.setEditable(false);

        this.txtContrPriv.setEditable(false);
        this.txtOtor.setEditable(false);
        this.txtFavor.setEditable(false);
        this.txtInsti.setEditable(false);
        this.txtLugar.setEditable(false);
        this.txtdia.setEditable(false);
        this.txtAño.setEditable(false);
        this.txtOtros.setEditable(false);
            this.btnGuardar.setEnabled(false);
            this.btnImprimir.setEnabled(false);
            this.btnUsu.setEnabled(false);
        }
         public void activa(){
            //this.txtSolicitud.setText("");
            this.txtSolicitud.setEditable(true);
            this.txtNumDoc.setEditable(true);
            this.txtNom.setEditable(true);
            this.txtContrPriv.setEditable(true);
        this.txtOtor.setEditable(true);
        this.txtFavor.setEditable(true);
        this.txtInsti.setEditable(true);
        this.txtLugar.setEditable(true);
        this.txtdia.setEditable(true);
        this.txtAño.setEditable(true);
        this.txtOtros.setEditable(true);
            this.btnGuardar.setEnabled(true);
            //this.btnImprimir.setEnabled(true);
            this.btnUsu.setEnabled(true);
        }

      public void limpiar(){
        this.txtNumDoc.setText("");
        this.txtNom.setText("");
        this.lblCod.setText("");
        this.txtContrPriv.setText("");
        this.txtOtor.setText("");
        this.txtFavor.setText("");
        this.txtInsti.setText("");
        this.txtLugar.setText("");
        this.txtdia.setText("");
        this.txtAño.setText("");
        this.txtOtros.setText("");
        this.btnImprimir.setEnabled(false);
        desactiva();
      }
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jPanel5 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        txtOtor = new javax.swing.JTextField();
        txtFavor = new javax.swing.JTextField();
        txtContrPriv = new javax.swing.JTextField();
        txtInsti = new javax.swing.JTextField();
        jPanel6 = new javax.swing.JPanel();
        jLabel16 = new javax.swing.JLabel();
        txtLugar = new javax.swing.JTextField();
        jLabel22 = new javax.swing.JLabel();
        cboxMes = new javax.swing.JComboBox();
        jLabel19 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtOtros = new javax.swing.JTextArea();
        txtAño = new javax.swing.JTextField();
        txtdia = new javax.swing.JTextField();
        btnNuevo = new javax.swing.JButton();
        btnImprimir = new javax.swing.JButton();
        btnGuardar = new javax.swing.JButton();
        jLabel23 = new javax.swing.JLabel();
        txtSolicitud = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        txtNumDoc = new javax.swing.JTextField();
        btnUsu = new javax.swing.JButton();
        txtNom = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        lblCod = new javax.swing.JLabel();
        lblIdSol = new javax.swing.JLabel();
        btnCancelar = new javax.swing.JButton();
        btnVer = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        labelIdSol = new javax.swing.JLabel();
        btnChangeDat = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 22)); // NOI18N
        jLabel1.setText("Enace");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 11, -1, -1));

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)), "Datos del documento", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 12))); // NOI18N

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel2.setText("Contrato Privado:");

        jLabel14.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel14.setText("Otorgante:");

        jLabel15.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel15.setText("Favorecido:");

        jLabel21.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel21.setText("Institución:");

        txtOtor.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        txtOtor.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtOtorKeyPressed(evt);
            }
        });

        txtFavor.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        txtFavor.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtFavorKeyPressed(evt);
            }
        });

        txtContrPriv.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        txtContrPriv.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtContrPrivKeyPressed(evt);
            }
        });

        txtInsti.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        txtInsti.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtInstiKeyPressed(evt);
            }
        });

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtContrPriv, javax.swing.GroupLayout.DEFAULT_SIZE, 253, Short.MAX_VALUE))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addComponent(jLabel14)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtOtor, javax.swing.GroupLayout.DEFAULT_SIZE, 287, Short.MAX_VALUE))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addComponent(jLabel15)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtFavor, javax.swing.GroupLayout.DEFAULT_SIZE, 286, Short.MAX_VALUE))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addComponent(jLabel21)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtInsti, javax.swing.GroupLayout.DEFAULT_SIZE, 287, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtContrPriv, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel14)
                    .addComponent(txtOtor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel15)
                    .addComponent(txtFavor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel21)
                    .addComponent(txtInsti, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(32, Short.MAX_VALUE))
        );

        jLabel16.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel16.setText("Lugar:");

        txtLugar.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        txtLugar.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtLugarKeyPressed(evt);
            }
        });

        jLabel22.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel22.setText("Fecha de Contrato Privado:");

        cboxMes.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        cboxMes.setModel(new javax.swing.DefaultComboBoxModel(new String[] { " ", "ENERO", "FEBRERO", "MARZO", "ABRIL", "MAYO", "JUNIO", "JULIO", "AGOSTO", "SETIEMBRE", "OCTUBRE", "NOVIEMBRE", "DICIEMBRE" }));
        cboxMes.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                cboxMesKeyPressed(evt);
            }
        });

        jLabel19.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel19.setText("Mes");

        jLabel18.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel18.setText("Dia");

        jLabel20.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel20.setText("Año");

        jScrollPane1.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_ALWAYS);

        txtOtros.setColumns(20);
        txtOtros.setRows(5);
        jScrollPane1.setViewportView(txtOtros);

        txtAño.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        txtAño.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtAñoKeyPressed(evt);
            }
        });

        txtdia.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtdiaKeyPressed(evt);
            }
        });

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addComponent(jLabel16)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtLugar, javax.swing.GroupLayout.DEFAULT_SIZE, 382, Short.MAX_VALUE))
                    .addComponent(jLabel22)
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addComponent(jLabel18)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtdia, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel19)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cboxMes, 0, 223, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel20)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtAño, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 420, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel16)
                    .addComponent(txtLugar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel22)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel18)
                    .addComponent(cboxMes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtAño, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtdia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel19)
                    .addComponent(jLabel20))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(29, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jPanel6, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel5, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(14, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 144, 860, 200));

        btnNuevo.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        btnNuevo.setText("Nuevo");
        btnNuevo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNuevoActionPerformed(evt);
            }
        });
        getContentPane().add(btnNuevo, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 70, 130, 60));

        btnImprimir.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        btnImprimir.setText("Imprimir");
        btnImprimir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnImprimirActionPerformed(evt);
            }
        });
        getContentPane().add(btnImprimir, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 370, 130, 40));

        btnGuardar.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        btnGuardar.setText("Guardar");
        btnGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGuardarActionPerformed(evt);
            }
        });
        getContentPane().add(btnGuardar, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 370, 130, 40));

        jLabel23.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel23.setText("Solicitud N°:");
        getContentPane().add(jLabel23, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 30, -1, -1));
        getContentPane().add(txtSolicitud, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 30, 75, -1));

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel4.setText("N° Documento:");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 57, -1, -1));

        txtNumDoc.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        txtNumDoc.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtNumDocKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtNumDocKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtNumDocKeyTyped(evt);
            }
        });
        getContentPane().add(txtNumDoc, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 58, 179, -1));

        btnUsu.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        btnUsu.setText("BUSCAR SOLICITANTE");
        btnUsu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUsuActionPerformed(evt);
            }
        });
        getContentPane().add(btnUsu, new org.netbeans.lib.awtextra.AbsoluteConstraints(285, 57, -1, -1));

        txtNom.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        txtNom.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtNomKeyPressed(evt);
            }
        });
        getContentPane().add(txtNom, new org.netbeans.lib.awtextra.AbsoluteConstraints(61, 86, 460, -1));

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel3.setText("Nombre:");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 89, -1, -1));

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel5.setText("Codigo Usuario:");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 116, -1, -1));

        lblCod.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        lblCod.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        getContentPane().add(lblCod, new org.netbeans.lib.awtextra.AbsoluteConstraints(104, 113, 81, 18));

        lblIdSol.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        getContentPane().add(lblIdSol, new org.netbeans.lib.awtextra.AbsoluteConstraints(850, 420, 64, 20));

        btnCancelar.setText("Cancelar");
        btnCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelarActionPerformed(evt);
            }
        });
        getContentPane().add(btnCancelar, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 370, 130, 40));

        btnVer.setText("Visualizar Solicitud");
        btnVer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVerActionPerformed(evt);
            }
        });
        getContentPane().add(btnVer, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 80, 150, -1));

        jButton1.setText("ReImprimir Solicitud");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 110, 150, -1));

        labelIdSol.setText("labelIdSol");
        getContentPane().add(labelIdSol, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 120, 80, -1));

        btnChangeDat.setText("Cambiar Datos");
        btnChangeDat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnChangeDatActionPerformed(evt);
            }
        });
        getContentPane().add(btnChangeDat, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 370, 130, 40));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtOtorKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtOtorKeyPressed
        if(KeyEvent.VK_ENTER == evt.getKeyCode()){
            txtFavor.requestFocus();
        }
}//GEN-LAST:event_txtOtorKeyPressed

    private void txtFavorKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtFavorKeyPressed
        if(KeyEvent.VK_ENTER == evt.getKeyCode()){
            txtInsti.requestFocus();
        }
}//GEN-LAST:event_txtFavorKeyPressed

    private void txtContrPrivKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtContrPrivKeyPressed
        if(KeyEvent.VK_ENTER == evt.getKeyCode()){
            txtOtor.requestFocus();
        }
}//GEN-LAST:event_txtContrPrivKeyPressed

    private void txtInstiKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtInstiKeyPressed
        if(KeyEvent.VK_ENTER == evt.getKeyCode()){
            txtLugar.requestFocus();
        }
}//GEN-LAST:event_txtInstiKeyPressed

    private void txtLugarKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtLugarKeyPressed
        if(KeyEvent.VK_ENTER == evt.getKeyCode()){
            txtdia.requestFocus();
        }
}//GEN-LAST:event_txtLugarKeyPressed

    private void cboxMesKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_cboxMesKeyPressed
        if(KeyEvent.VK_ENTER == evt.getKeyCode()){
            txtAño.requestFocus();
        }
}//GEN-LAST:event_cboxMesKeyPressed

    private void txtAñoKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtAñoKeyPressed
        if(KeyEvent.VK_ENTER == evt.getKeyCode()){
            txtOtros.requestFocus();
        }
}//GEN-LAST:event_txtAñoKeyPressed

    private void btnNuevoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNuevoActionPerformed
        activa();
        this.txtNumDoc.requestFocus();
        int solic=0,esc=0;
        try{
            con.conectar();
            ResultSet res=con.consulta("SELECT max(codSol) FROM solicitudes");
            res.next();
            solic=Integer.parseInt(res.getString(1));
            res=con.consulta("SELECT count(idSol) FROM enace");
            res.next();
            esc=Integer.parseInt(res.getString(1));
            con.cierraConexion();
        }catch(SQLException e){
            System.out.println(e);
        }
        txtSolicitud.setText(String.valueOf(solic+1));
        lblIdSol.setText(String.valueOf(esc+1));
        this.txtNumDoc.setText("");
        this.txtNom.setText("");
        this.lblCod.setText("");
        this.txtContrPriv.setText("");
        this.txtOtor.setText("");
        this.txtFavor.setText("");
        this.txtInsti.setText("");
        this.txtLugar.setText("");
        this.txtdia.setText("");
        this.txtAño.setText("");
        this.txtOtros.setText("");
}//GEN-LAST:event_btnNuevoActionPerformed

    private void btnImprimirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnImprimirActionPerformed
        String num_sol = this.txtSolicitud.getText();
        jasper.ejecutarReporte(num_sol);
}//GEN-LAST:event_btnImprimirActionPerformed

    private void btnGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuardarActionPerformed
        cod = Integer.parseInt(lblCod.getText());
        idsol =Integer.parseInt(lblIdSol.getText());
        
        num_solicitud = this.txtSolicitud.getText();
        int codTipSol=4;
        //
        conPri = txtContrPriv.getText();
        otor = txtOtor.getText();
        favor = txtFavor.getText();
        inst=txtInsti.getText();
        lugar=txtLugar.getText();
        dia = this.txtdia.getText();
        mes = cboxMes.getSelectedItem().toString();
        año = txtAño.getText();
        otros = txtOtros.getText();
        try{
            int rpta = JOptionPane.showConfirmDialog(rootPane, "¿Estas seguro de guardar?","ARP Sistema",JOptionPane.YES_NO_OPTION);
            if(rpta == 0){
                con.conectar();
                
                con.insertar("INSERT INTO enace (idSol,conPri,otorgante,favorecido,institucion,lugar,dia,mes,anio,obs) VALUES (null,'"+conPri+"','"+otor+"','"+favor+"','"+inst+"','"+lugar+"','"+dia+"','"+mes+"','"+año+"','"+otros+"');");             
                con.insertar("INSERT INTO solicitudes(codSol,codUsu,codTipSol,idSol) VALUES ('"+num_solicitud+"','"+cod+"','"+codTipSol+"','"+idsol+"');");
                
                this.btnGuardar.setEnabled(false);
                this.btnImprimir.setEnabled(true);
                
                con.cierraConexion();
            }
        }catch(HeadlessException | SQLException e){
            JOptionPane.showMessageDialog(rootPane, "Error Guardando. " +e);
        }
}//GEN-LAST:event_btnGuardarActionPerformed

    private void txtNumDocKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtNumDocKeyPressed
        if(KeyEvent.VK_ENTER == evt.getKeyCode()){
            btnUsu.doClick();
        }
}//GEN-LAST:event_txtNumDocKeyPressed

    private void txtNumDocKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtNumDocKeyReleased
        if(txtNumDoc.getText().length()>7){
            btnUsu.doClick();
        }
}//GEN-LAST:event_txtNumDocKeyReleased

    private void txtNumDocKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtNumDocKeyTyped
        int n = (int)evt.getKeyChar();
        if(n>=48 && n<=57 || n==13 || n==127){

        }else{
            evt.setKeyChar((char)KeyEvent.VK_CLEAR);
        }
}//GEN-LAST:event_txtNumDocKeyTyped

    private void btnUsuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUsuActionPerformed
       int numero = txtNumDoc.getText().length();
        String dni2 = null;
        
        if (numero <8){
            JOptionPane.showMessageDialog(rootPane, "Numero de Digitos de DNI Menor que 8 Numeros y de RUC es 11");
            this.txtNumDoc.requestFocus();
        }else{
            if (numero==8)
            {
            String dni=this.txtNumDoc.getText();
            try{
                con.conectar();
               
               
                ResultSet rs=con.consulta("SELECT codUsu,CONCAT(nombre,' ',apePat,' ',apeMat) AS nombre FROM usuarios WHERE numDoc='"+dni+"' LIMIT 0,1;");
                rs.next();
                this.txtNom.setText(rs.getString(2));
                this.lblCod.setText(rs.getString(1));
                con.cierraConexion();
            }catch(SQLException e){
                JOptionPane.showMessageDialog(rootPane, "Usuario no encontrado","Administrador de Sistema",JOptionPane.INFORMATION_MESSAGE);
                dni2 = this.txtNumDoc.getText();
                dialogNuevoUsuario p=new dialogNuevoUsuario(null,true,dni2);
                p.setVisible(true);
            }
            

        }else {if (numero==11){
            String ruc=this.txtNumDoc.getText();
            try{
                con.conectar();
                ResultSet rs=con.consulta("SELECT codUsu, apeMat from usuarios where numDoc='"+ruc+"' LIMIT 0,1;");
                rs.next();
                this.txtNom.setText(rs.getString(2));
                this.lblCod.setText(rs.getString(1));
                con.cierraConexion();
            }catch(SQLException e){
                JOptionPane.showMessageDialog(rootPane, "Empresa no registrada","Administrador del Sitema", JOptionPane.INFORMATION_MESSAGE);
                // = this.txtNunDNI.getText();
                dialogNuevoJuridico p=new dialogNuevoJuridico(null, true, ruc);
                p.setVisible(true);
            }
        }}
        }
}//GEN-LAST:event_btnUsuActionPerformed
    
    private void txtNomKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtNomKeyPressed
        if(KeyEvent.VK_ENTER == evt.getKeyCode()){
            txtContrPriv.requestFocus();
        }
}//GEN-LAST:event_txtNomKeyPressed

    private void btnCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarActionPerformed
        // TODO add your handling code here:
        limpiar();
}//GEN-LAST:event_btnCancelarActionPerformed

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        // TODO add your handling code here:
        desactiva();
    }//GEN-LAST:event_formWindowOpened

    private void txtdiaKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtdiaKeyPressed
        // TODO add your handling code here:
        if(KeyEvent.VK_ENTER == evt.getKeyCode()){
            this.cboxMes.requestFocus();
        }
    }//GEN-LAST:event_txtdiaKeyPressed

    private void btnVerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVerActionPerformed
        // TODO add your handling code here:
        ver_solicitud = JOptionPane.showInputDialog("Ingrese Numero de Solicitud a visualizar");

        this.txtNumDoc.setEditable(true);
        this.btnUsu.setEnabled(true);
        this.txtContrPriv.setEditable(true);
        this.txtFavor.setEditable(true);
        this.txtOtor.setEditable(true);
        this.txtInsti.setEditable(true);
        this.txtOtros.setEditable(true);
        this.txtdia.setEditable(true);

        this.cboxMes.setSelectedIndex(0);
        this.txtAño.setEditable(true);

        this.txtLugar.setEditable(true);


        this.btnGuardar.setVisible(false);
        this.btnChangeDat.setVisible(true);
        try{
            con.conectar();
            ResultSet res = con.consulta("SELECT s.codSol, s.idSol, CONCAT(u.nombre,' ', u.apePat,' ',apeMat) AS usuario,u.codUsu, u.codDis, u.numDoc, u.direccion,en.conPri, en.otorgante, en.favorecido, en.institucion, en.lugar, en.dia, en.mes, en.anio, en.obs FROM solicitudes AS s, usuarios AS u,enace AS en WHERE s.idSol = en.idSol AND s.codUsu = u.codUsu AND s.codSol = '"+ver_solicitud+"';");
            res.next();
            this.txtSolicitud.setText(res.getString("codSol"));
            this.txtNumDoc.setText(res.getString("numDoc"));
            this.lblCod.setText(res.getString("codUsu"));
            this.txtNom.setText(res.getString("usuario"));

            this.txtContrPriv.setText(res.getString("conPri"));
            this.txtOtor.setText(res.getString("otorgante"));
            this.txtFavor.setText(res.getString("favorecido"));
            this.txtInsti.setText(res.getString("institucion"));
            this.txtLugar.setText(res.getString("Lugar"));
            this.txtdia.setText(res.getString("dia"));
            this.cboxMes.setSelectedItem(res.getString("mes"));
            this.txtAño.setText(res.getString("anio"));
            this.txtOtros.setText(res.getString("obs"));
            this.labelIdSol.setText(res.getString("idSol"));
            con.cierraConexion();
        }catch(Exception e){
            JOptionPane.showMessageDialog(rootPane, "Error Consultando. " + e);
        }
}//GEN-LAST:event_btnVerActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        String solicitudD = JOptionPane.showInputDialog("Escriba el Numero de Solicitud");
        String num_sol = solicitudD;
        jasper.ejecutarReporte(num_sol);
}//GEN-LAST:event_jButton1ActionPerformed

    private void btnChangeDatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnChangeDatActionPerformed
        // Activa los cuadros

        codUsu = this.labelIdSol.getText();
        idsol =Integer.parseInt(lblIdSol.getText());
        // Recoje los datos
        NumIdSol = this.labelIdSol.getText();
        num_solicitud = this.txtSolicitud.getText();

        conPri=this.txtContrPriv.getText().toUpperCase();
        otor = this.txtOtor.getText().toUpperCase();
        favor = this.txtFavor.getText().toUpperCase();
        inst = this.txtInsti.getText().toUpperCase();
        lugar=this.txtLugar.getText().toUpperCase();
        dia = this.txtdia.getText().toUpperCase();
        mes = this.cboxMes.getSelectedItem().toString();
        año = this.txtAño.getText().toUpperCase();
        otros = this.txtOtros.getText().toUpperCase();

        int rpta1 = JOptionPane.showConfirmDialog(rootPane,"¿Esta seguro de realizar estos cambios?","ARP Sistema",JOptionPane.YES_NO_OPTION);
        if(rpta1 == 0){
            try{
                con.conectar();
                con.actualizar("UPDATE `recepcion`.`enace` SET `conPri`='"+conPri+"', `otorgante`='"+otor+"', `favorecido`='"+favor+"', `institucion`='"+inst+"', `lugar`='"+lugar+"', `dia`='"+dia+"', `mes`='"+mes+"', `anio`='"+año+"', `obs`='"+otros+"'WHERE idSol = '"+NumIdSol+"';");
                con.actualizar("UPDATE solicitudes SET codUsu = '"+codUsu+"', idSol = '"+NumIdSol+"' WHERE codSol = '"+num_solicitud+"';");
                JOptionPane.showMessageDialog(rootPane, "Datos Modificados Satisfactotiamente");
                //con.cierraConexion();
            }catch(Exception e){
                JOptionPane.showMessageDialog(rootPane, "Error Cambiando datos. " + e);
            }
        }
        this.btnChangeDat.setVisible(false);
        this.btnGuardar.setVisible(true);
        this.btnGuardar.setEnabled(false);
        this.btnImprimir.setEnabled(true);
}//GEN-LAST:event_btnChangeDatActionPerformed

    /**
    * @param args the command line arguments
    */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                Enace dialog = new Enace(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCancelar;
    private javax.swing.JButton btnChangeDat;
    private javax.swing.JButton btnGuardar;
    private javax.swing.JButton btnImprimir;
    private javax.swing.JButton btnNuevo;
    private javax.swing.JButton btnUsu;
    private javax.swing.JButton btnVer;
    private javax.swing.JComboBox cboxMes;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel labelIdSol;
    private javax.swing.JLabel lblCod;
    private javax.swing.JLabel lblIdSol;
    private javax.swing.JTextField txtAño;
    private javax.swing.JTextField txtContrPriv;
    private javax.swing.JTextField txtFavor;
    private javax.swing.JTextField txtInsti;
    private javax.swing.JTextField txtLugar;
    private javax.swing.JTextField txtNom;
    private javax.swing.JTextField txtNumDoc;
    private javax.swing.JTextField txtOtor;
    private javax.swing.JTextArea txtOtros;
    private javax.swing.JTextField txtSolicitud;
    private javax.swing.JTextField txtdia;
    // End of variables declaration//GEN-END:variables

}
