package sistemasolicitudes;

import java.awt.event.KeyEvent;
import java.sql.ResultSet;
import java.sql.SQLException;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

public class ExpedienteArchivado2 extends javax.swing.JDialog {
    
    conexion con = new conexion();
    int idsol, codigoNotario;
    String expArchivado,tipExp, codNot, materia,juzgado, otorgante, favorecido, causante, seguido, lugar, anio, otros, dia, mes, num_solicitud, ver_solicitud, cod, obs, contra;
    
    private ReportExpedienteArchivado jasper;
    
    notarios2 nt2 = new notarios2();
    Object[][] datNot;
    int fila =-1;
    
    public ExpedienteArchivado2(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        
        Desactiva();
        
        lblIdSol.setVisible(false);
        lblcodigoUsuario.setVisible(false);
        lblCod.setVisible(false);
        this.txtCodNot.setVisible(false);
        btnCambiarDatos.setVisible(false);
        
        jasper = new ReportExpedienteArchivado();  
        
    }
    
    private void Desactiva(){
        this.txtSolicitud.setEnabled(false);
        this.txtNumDoc.setEnabled(false);
        this.txtNom.setEnabled(false);
        this.txtExpedienteArchivado.setEnabled(false);
        this.txtBuscaNotario.setEnabled(false);
        this.txtNotario.setEnabled(false);
        this.txtfecini.setEnabled(false);
        this.txtfecfin.setEnabled(false);
        this.txtOtorgante.setEnabled(false);
        this.txtFavorecido.setEnabled(false);
        this.txtSeguido.setEnabled(false);
        this.txtCausante.setEnabled(false);
        this.txtDia.setEnabled(false);
        this.cboxMes.setEnabled(false);
        this.txtAño.setEnabled(false);
        this.txtOtros.setEnabled(false);
        
        this.btnUsu.setEnabled(false);
        this.btnCambiarDatos.setEnabled(false);
        this.btnGuardar.setEnabled(false);
        this.btnImprimir.setEnabled(false);
    }

    public void activa(){
        this.txtSolicitud.setEnabled(true);
        this.txtNumDoc.setEnabled(true);
        this.txtNom.setEnabled(true);
        this.txtExpedienteArchivado.setEnabled(true);
        this.txtBuscaNotario.setEnabled(true);
        this.txtNotario.setEnabled(true);
        this.txtfecini.setEnabled(true);
        this.txtfecfin.setEnabled(true);
        this.txtOtorgante.setEnabled(true);
        this.txtFavorecido.setEnabled(true);
        this.txtSeguido.setEnabled(true);
        this.txtCausante.setEnabled(true);
        this.txtDia.setEnabled(true);
        this.cboxMes.setEnabled(true);
        this.txtAño.setEnabled(true);
        this.txtOtros.setEnabled(true);
        this.btnUsu.setEnabled(true);
        this.btnCambiarDatos.setEnabled(false);
        this.btnGuardar.setEnabled(true);
        this.btnImprimir.setEnabled(true);
        
        this.txtSolicitud.setEnabled(false);
        Desactiva();
    }
    
    public void limpiar(){
        this.txtNumDoc.setText("");
        this.txtNom.setText("");
        this.lblCod.setText("");
        this.lblIdSol.setText("");
        this.txtExpedienteArchivado.setText("");
        this.txtOtorgante.setText("");
        this.txtFavorecido.setText("");
        this.txtSeguido.setText("");
        this.txtCausante.setText("");
        this.txtLugar.setText("");
        this.txtJuzgado.setText("");
        this.txtOtros.setText("");
        this.txtDia.setText("");
        this.cboxMes.setSelectedIndex(0);
        this.txtAño.setText("");
                
        this.btnImprimir.setEnabled(false);
        Desactiva();
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel23 = new javax.swing.JLabel();
        txtSolicitud = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jPanel5 = new javax.swing.JPanel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        txtOtorgante = new javax.swing.JTextField();
        txtFavorecido = new javax.swing.JTextField();
        txtSeguido = new javax.swing.JTextField();
        txtExpedienteArchivado = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        txtCausante = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        txtBuscaNotario = new javax.swing.JTextField();
        lblcodNot = new javax.swing.JLabel();
        txtCodNot = new javax.swing.JTextField();
        jScrollPane2 = new javax.swing.JScrollPane();
        Tabla = new javax.swing.JTable();
        jLabel9 = new javax.swing.JLabel();
        txtNotario = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        txtfecini = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        txtfecfin = new javax.swing.JTextField();
        jLabel18 = new javax.swing.JLabel();
        txtDia = new javax.swing.JTextField();
        jLabel19 = new javax.swing.JLabel();
        cboxMes = new javax.swing.JComboBox();
        jLabel20 = new javax.swing.JLabel();
        txtAño = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtOtros = new javax.swing.JTextArea();
        jLabel2 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        txtJuzgado = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        txtLugar = new javax.swing.JTextField();
        txtNumDoc = new javax.swing.JTextField();
        btnUsu = new javax.swing.JButton();
        txtNom = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        lblcodigoUsuario = new javax.swing.JLabel();
        btnGuardar = new javax.swing.JButton();
        lblCod = new javax.swing.JLabel();
        btnImprimir = new javax.swing.JButton();
        lblIdSol = new javax.swing.JLabel();
        btnNuevo = new javax.swing.JButton();
        btnVisulaizar = new javax.swing.JButton();
        LabelIdSol = new javax.swing.JLabel();
        btnCambiarDatos = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel23.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel23.setText("Solicitud N°:");
        getContentPane().add(jLabel23, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 50, -1, -1));

        txtSolicitud.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        txtSolicitud.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtSolicitudActionPerformed(evt);
            }
        });
        getContentPane().add(txtSolicitud, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 40, 89, -1));

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel4.setText("N° Documento:");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 80, -1, -1));

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)), "Datos del documento", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 12))); // NOI18N

        jPanel5.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel14.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel14.setText("Otorgante:");
        jPanel5.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 250, -1, -1));

        jLabel15.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel15.setText("A favor de:");
        jPanel5.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 280, -1, -1));

        jLabel21.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel21.setText("Seguido por:");
        jPanel5.add(jLabel21, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 310, -1, -1));

        txtOtorgante.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        txtOtorgante.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtOtorganteKeyPressed(evt);
            }
        });
        jPanel5.add(txtOtorgante, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 250, 380, -1));

        txtFavorecido.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        txtFavorecido.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtFavorecidoKeyPressed(evt);
            }
        });
        jPanel5.add(txtFavorecido, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 280, 380, -1));

        txtSeguido.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        txtSeguido.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtSeguidoKeyPressed(evt);
            }
        });
        jPanel5.add(txtSeguido, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 310, 380, -1));

        txtExpedienteArchivado.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        txtExpedienteArchivado.setText("EXPEDIENTE ARCHIVADO");
        txtExpedienteArchivado.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtExpedienteArchivadoKeyPressed(evt);
            }
        });
        jPanel5.add(txtExpedienteArchivado, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 10, 287, -1));
        jPanel5.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(65, 40, -1, -1));

        jLabel8.setText("Causante:");
        jPanel5.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 340, -1, -1));

        txtCausante.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtCausanteKeyPressed(evt);
            }
        });
        jPanel5.add(txtCausante, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 340, 380, -1));

        jLabel13.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel13.setText("Notario:");
        jPanel5.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 40, -1, -1));

        txtBuscaNotario.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txtBuscaNotario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtBuscaNotarioActionPerformed(evt);
            }
        });
        txtBuscaNotario.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtBuscaNotarioKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtBuscaNotarioKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtBuscaNotarioKeyTyped(evt);
            }
        });
        jPanel5.add(txtBuscaNotario, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 40, 410, -1));

        lblcodNot.setText("CodNot");
        jPanel5.add(lblcodNot, new org.netbeans.lib.awtextra.AbsoluteConstraints(730, 40, -1, -1));

        txtCodNot.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jPanel5.add(txtCodNot, new org.netbeans.lib.awtextra.AbsoluteConstraints(770, 40, 110, -1));

        Tabla.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        Tabla.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null}
            },
            new String [] {
                "Codigo", "Notario", "Provincia"
            }
        ));
        Tabla.setToolTipText("Lista de Notarios");
        Tabla.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                TablaMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(Tabla);

        jPanel5.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 70, 870, 110));

        jLabel9.setText("Notario:");
        jPanel5.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 190, -1, -1));

        txtNotario.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jPanel5.add(txtNotario, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 190, 450, -1));

        jLabel10.setText("Fec. Ini:");
        jPanel5.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 190, -1, -1));
        jPanel5.add(txtfecini, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 190, 70, -1));

        jLabel11.setText("Fec. Fin:");
        jPanel5.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 190, -1, -1));
        jPanel5.add(txtfecfin, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 190, 70, -1));

        jLabel18.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel18.setText("Dia");
        jPanel5.add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 380, -1, -1));

        txtDia.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtDiaKeyPressed(evt);
            }
        });
        jPanel5.add(txtDia, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 380, 35, -1));

        jLabel19.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel19.setText("Mes");
        jPanel5.add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 380, -1, -1));

        cboxMes.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        cboxMes.setModel(new javax.swing.DefaultComboBoxModel(new String[] { " ", "ENERO", "FEBRERO", "MARZO", "ABRIL", "MAYO", "JUNIO", "JULIO", "AGOSTO", "SETIEMBRE", "OCTUBRE", "NOVIEMBRE", "DICIEMBRE" }));
        cboxMes.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                cboxMesKeyPressed(evt);
            }
        });
        jPanel5.add(cboxMes, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 380, 110, -1));

        jLabel20.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel20.setText("Año");
        jPanel5.add(jLabel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 380, -1, -1));

        txtAño.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        txtAño.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtAñoKeyPressed(evt);
            }
        });
        jPanel5.add(txtAño, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 380, 70, -1));

        jScrollPane1.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_ALWAYS);

        txtOtros.setColumns(20);
        txtOtros.setRows(5);
        txtOtros.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtOtrosKeyPressed(evt);
            }
        });
        jScrollPane1.setViewportView(txtOtros);

        jPanel5.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 340, 350, 70));

        jLabel2.setText("Tipo de Expediente:");
        jPanel5.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 10, -1, -1));

        jLabel5.setText("Observaciones:");
        jPanel5.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 320, -1, -1));

        jLabel7.setText("Juzgado:");
        jPanel5.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 280, -1, 20));

        txtJuzgado.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtJuzgadoKeyPressed(evt);
            }
        });
        jPanel5.add(txtJuzgado, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 280, 330, -1));

        jLabel12.setText("Lugar:");
        jPanel5.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 250, -1, -1));
        jPanel5.add(txtLugar, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 250, 160, -1));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, 427, Short.MAX_VALUE)
                .addContainerGap())
        );

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 150, 950, 460));

        txtNumDoc.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        txtNumDoc.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtNumDocKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtNumDocKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtNumDocKeyTyped(evt);
            }
        });
        getContentPane().add(txtNumDoc, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 70, 179, 30));

        btnUsu.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        btnUsu.setText("BUSCAR SOLICITANTE");
        btnUsu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUsuActionPerformed(evt);
            }
        });
        getContentPane().add(btnUsu, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 70, -1, 30));

        txtNom.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        txtNom.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtNomKeyPressed(evt);
            }
        });
        getContentPane().add(txtNom, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 112, 470, 30));

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel3.setText("Nombre:");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 120, -1, -1));

        lblcodigoUsuario.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        lblcodigoUsuario.setText("Codigo Usuario:");
        getContentPane().add(lblcodigoUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(800, 40, -1, -1));

        btnGuardar.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btnGuardar.setText("Guardar");
        btnGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGuardarActionPerformed(evt);
            }
        });
        getContentPane().add(btnGuardar, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 630, 140, 50));

        lblCod.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        lblCod.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        getContentPane().add(lblCod, new org.netbeans.lib.awtextra.AbsoluteConstraints(890, 40, 81, 18));

        btnImprimir.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btnImprimir.setText("Imprimir");
        btnImprimir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnImprimirActionPerformed(evt);
            }
        });
        getContentPane().add(btnImprimir, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 630, 140, 50));

        lblIdSol.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        getContentPane().add(lblIdSol, new org.netbeans.lib.awtextra.AbsoluteConstraints(1000, 680, 60, 18));

        btnNuevo.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btnNuevo.setText("Nuevo");
        btnNuevo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNuevoActionPerformed(evt);
            }
        });
        getContentPane().add(btnNuevo, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 80, 150, 60));

        btnVisulaizar.setText("Visualizar Expediente");
        btnVisulaizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVisulaizarActionPerformed(evt);
            }
        });
        getContentPane().add(btnVisulaizar, new org.netbeans.lib.awtextra.AbsoluteConstraints(790, 80, 180, 30));

        LabelIdSol.setText("LabelIdSol");
        getContentPane().add(LabelIdSol, new org.netbeans.lib.awtextra.AbsoluteConstraints(940, 680, -1, -1));

        btnCambiarDatos.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btnCambiarDatos.setText("Cambiar Datos");
        btnCambiarDatos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCambiarDatosActionPerformed(evt);
            }
        });
        getContentPane().add(btnCambiarDatos, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 630, 170, 50));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 22)); // NOI18N
        jLabel1.setText("Expediente Archivado");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 30, 280, -1));

        jButton1.setText("ReImprimir Solicitud");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(790, 113, 180, 30));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtSolicitudActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtSolicitudActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtSolicitudActionPerformed

    private void txtNumDocKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtNumDocKeyPressed
        if(KeyEvent.VK_ENTER == evt.getKeyCode()){
            btnUsu.doClick();
        }
    }//GEN-LAST:event_txtNumDocKeyPressed

    private void txtNumDocKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtNumDocKeyReleased
        if(txtNumDoc.getText().length()>7){
            btnUsu.doClick();
        }
    }//GEN-LAST:event_txtNumDocKeyReleased

    private void txtNumDocKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtNumDocKeyTyped
        int n = (int)evt.getKeyChar();
        if(n>=48 && n<=57 || n==13 || n==127){
        }else{
            evt.setKeyChar((char)KeyEvent.VK_CLEAR);
        }
    }//GEN-LAST:event_txtNumDocKeyTyped

    private void btnUsuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUsuActionPerformed
        int numero = txtNumDoc.getText().length();
        String dni2 = null;

        if (numero <8){
            JOptionPane.showMessageDialog(rootPane, "Numero de Digitos de DNI Menor que 8 Numeros y de RUC es 11");
            this.txtNumDoc.requestFocus();
        }else{
            if (numero==8)
            {
                String dni=this.txtNumDoc.getText();
                try{
                    con.conectar();

                    ResultSet rs=con.consulta("SELECT codUsu,CONCAT(nombre,' ',apePat,' ',apeMat) AS nombre FROM usuarios WHERE numDoc='"+dni+"' LIMIT 0,1;");
                    rs.next();
                    this.txtNom.setText(rs.getString(2));
                    this.lblCod.setText(rs.getString(1));
                    con.cierraConexion();
                }catch(SQLException e){
                    JOptionPane.showMessageDialog(rootPane, "Usuario no encontrado","Administrador de Sistema",JOptionPane.INFORMATION_MESSAGE);
                    dni2 = this.txtNumDoc.getText();
                    dialogNuevoUsuario p=new dialogNuevoUsuario(null,true,dni2);
                    p.setVisible(true);
                }

            }else {if (numero==11){
                String ruc=this.txtNumDoc.getText();
                try{
                    con.conectar();
                    ResultSet rs=con.consulta("SELECT codUsu, apeMat from usuarios where numDoc='"+ruc+"' LIMIT 0,1;");
                    rs.next();
                    this.txtNom.setText(rs.getString(2));
                    this.lblCod.setText(rs.getString(1));
                    con.cierraConexion();
                }catch(SQLException e){
                    JOptionPane.showMessageDialog(rootPane, "Empresa no registrada","Administrador del Sitema", JOptionPane.INFORMATION_MESSAGE);
                    // = this.txtNunDNI.getText();
                    dialogNuevoJuridico p=new dialogNuevoJuridico(null, true, ruc);
                    p.setVisible(true);
                }
            }}
        }
    }//GEN-LAST:event_btnUsuActionPerformed

    private void txtNomKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtNomKeyPressed
        if(KeyEvent.VK_ENTER == evt.getKeyCode()){
            txtExpedienteArchivado.requestFocus();
        }
    }//GEN-LAST:event_txtNomKeyPressed

    private void btnGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuardarActionPerformed
        
        cod = lblCod.getText();
        idsol =Integer.parseInt(lblIdSol.getText());
        int codTipSol = 5;
        
        tipExp        = this.txtExpedienteArchivado.getText().toUpperCase();
	num_solicitud = this.txtSolicitud.getText();
	expArchivado  = this.txtExpedienteArchivado.getText().toUpperCase();
	codNot        = this.txtCodNot.getText();
	otorgante     = this.txtOtorgante.getText().toUpperCase();
	favorecido    = this.txtFavorecido.getText().toUpperCase();
	seguido       = this.txtSeguido.getText().toUpperCase();
	causante      = this.txtCausante.getText().toUpperCase();
	juzgado       = this.txtJuzgado.getText().toUpperCase();
	lugar         = this.txtLugar.getText().toUpperCase();
	dia           = this.txtDia.getText().toUpperCase();
	mes           = this.cboxMes.getSelectedItem().toString().toUpperCase();
	anio          = this.txtAño.getText();
	otros         = this.txtOtros.getText().toUpperCase();

        int rpta = JOptionPane.showConfirmDialog(rootPane, "¿Estas seguro de Guardar?","ARP Sistema",JOptionPane.YES_NO_OPTION);
        if(rpta == 0){
            try{
                con.conectar();
                
                con.insertar("INSERT INTO exparchivado (tipExp,codNot,otorgante,favorecido,juzgado,seguido,causante,dia,mes,anio,obs) VALUES ('"+tipExp+"','"+codNot+"','"+otorgante+"','"+favorecido+"','"+juzgado+"','"+seguido+"','"+causante+"','"+dia+"','"+mes+"','"+anio+"','"+otros+"')");
                con.insertar("INSERT INTO solicitudes(codSol,codUsu,codTipSol,idSol) VALUES ('"+num_solicitud+"','"+cod+"','"+codTipSol+"','"+idsol+"');");
                
                con.cierraConexion();

                this.btnGuardar.setEnabled(false);
                this.btnImprimir.setEnabled(true);
            }catch(Exception e){
                JOptionPane.showMessageDialog(rootPane, "Error inesperado No Guardado. " + e);
            }
        }
    }//GEN-LAST:event_btnGuardarActionPerformed

    private void btnImprimirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnImprimirActionPerformed
        // TODO add your handling code here:
        
        String num_sol = this.txtSolicitud.getText();
        jasper.ejecutarReporte(num_sol);
    }//GEN-LAST:event_btnImprimirActionPerformed

    private void btnNuevoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNuevoActionPerformed
        activa();
        
        this.txtNumDoc.requestFocus();
        txtNumDoc.requestFocus();
        int solic=0,esc=0;
        try{
            con.conectar();
            ResultSet res=con.consulta("SELECT max(codSol) FROM solicitudes");
            res.next();
            solic=Integer.parseInt(res.getString(1));
            res=con.consulta("SELECT count(idSol) FROM exparchivado");
            res.next();
            esc=Integer.parseInt(res.getString(1));
            con.cierraConexion();
        }catch(SQLException e){
            System.out.println(e);
        }
        txtSolicitud.setText(String.valueOf(solic+1));
        lblIdSol.setText(String.valueOf(esc+1));
        txtNom.setText("");
        txtNumDoc.setText("");
        txtOtros.setText("");
        txtDia.setText("");
        cboxMes.setSelectedIndex(0);
        txtAño.setText("");
        txtExpedienteArchivado.setText("EXPEDIENTE ARCHIVADO");

        txtOtorgante.setText("");
        txtFavorecido.setText("");
        txtSeguido.setText("");

    }//GEN-LAST:event_btnNuevoActionPerformed

    private void btnVisulaizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVisulaizarActionPerformed
        // TODO add your handling code here:
        ver_solicitud = JOptionPane.showInputDialog("Ingrese Numero de Solicitud a visualizar");

        this.txtNumDoc.setEditable(true);
        this.btnUsu.setEnabled(true);
        this.btnGuardar.setVisible(false);
        
        try{
            con.conectar();
            ResultSet res = con.consulta("SELECT s.codSol,s.idSol, CONCAT(u.nombre,' ', u.apePat,' ',apeMat) AS usuario, u.codUsu, u.codDis, u.numDoc, u.direccion, ea.idSol,ea.tipExp,ea.codNot,ea.otorgante,ea.favorecido,ea.juzgado,ea.seguido,ea.causante,ea.lugar ,ea.dia,ea.mes,ea.anio,ea.obs,ea.contra FROM solicitudes AS s, usuarios AS u, exparchivado AS ea WHERE s.idSol = ea.idSol AND s.codUsu = u.codUsu AND s.codSol = "+ver_solicitud+";");
            res.next();
            this.txtSolicitud.setText(res.getString("codSol"));
            this.txtNumDoc.setText(res.getString("numDoc"));
            this.txtNom.setText(res.getString("usuario"));
            this.txtExpedienteArchivado.setText(res.getString("tipExp"));
            this.txtOtorgante.setText(res.getString("otorgante"));
            this.txtFavorecido.setText(res.getString("favorecido"));
            this.txtSeguido.setText(res.getString("seguido"));
            this.txtCausante.setText(res.getString("causante"));
            this.txtLugar.setText(res.getString("lugar"));
            this.txtJuzgado.setText(res.getString("juzgado"));
            this.txtDia.setText(res.getString("dia"));
            this.cboxMes.setSelectedItem(res.getString("mes"));
            this.txtAño.setText(res.getString("anio"));
            this.txtOtros.setText(res.getString("obs"));
            this.LabelIdSol.setText(res.getString("idSol"));
            this.lblCod.setText(res.getString("codUsu"));
        }catch(Exception e){
            JOptionPane.showMessageDialog(null, e);
        }
        activa();
        this.btnCambiarDatos.setVisible(true);
        this.btnCambiarDatos.setEnabled(true);
    }//GEN-LAST:event_btnVisulaizarActionPerformed

    private void btnCambiarDatosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCambiarDatosActionPerformed
        // TODO add your handling code here:
        cod = this.lblCod.getText();   //Codigo del usuario
        idsol =Integer.parseInt(this.LabelIdSol.getText());   //
        num_solicitud = this.txtSolicitud.getText();
        codNot = this.txtCodNot.getText();
        expArchivado = this.txtExpedienteArchivado.getText().toUpperCase();
        otorgante = this.txtOtorgante.getText().toUpperCase();
        favorecido = this.txtFavorecido.getText().toUpperCase();
        seguido = this.txtSeguido.getText().toUpperCase();
        causante = this.txtCausante.getText().toUpperCase();
        lugar = this.txtLugar.getText().toUpperCase();
        juzgado = this.txtJuzgado.getText().toUpperCase();
        causante = this.txtCausante.getText().toUpperCase();
        contra = "";
        dia = this.txtDia.getText().toUpperCase();
        mes = this.cboxMes.getSelectedItem().toString();
        anio = txtAño.getText().toUpperCase();
        otros = txtOtros.getText().toUpperCase();

        int rpta1 = JOptionPane.showConfirmDialog(rootPane,"¿Esta seguro de realizar estos cambios?","ARP Sistema",JOptionPane.YES_NO_OPTION);
        if(rpta1 == 0){
            try{
                con.conectar();
                con.actualizar("UPDATE exparchivado SET tipExp = '"+ expArchivado +"',codNot = '"+ codNot +"', otorgante = '"+ otorgante +"',favorecido = '"+ favorecido +"',juzgado = '"+ juzgado +"',seguido = '"+ seguido +"', causante = '"+ causante +"',lugar = '"+ lugar +"',dia = '"+ dia +"',mes = '"+ mes +"',anio = '"+ anio +"',obs = '"+ otros +"',contra = '"+ contra +"' WHERE idSol='"+idsol+"'");
                con.actualizar("UPDATE solicitudes SET codUsu = '"+cod+"', idSol = '"+idsol+"' WHERE codSol = '"+num_solicitud+"';");
                JOptionPane.showMessageDialog(rootPane, "Datos Modificados Satisfactotiamente");
                //con.cierraConexion();

            }catch(Exception e){
                JOptionPane.showMessageDialog(rootPane, "Error Cambiando datos. " + e);
            }
        }
        this.btnCambiarDatos.setVisible(false);
        this.btnGuardar.setEnabled(false);
        this.btnImprimir.setEnabled(true);
    }//GEN-LAST:event_btnCambiarDatosActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        String solicitudD = JOptionPane.showInputDialog("Escriba el Numero de Solicitud");
        jasper.ejecutarReporte(solicitudD);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void txtOtrosKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtOtrosKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtOtrosKeyPressed

    private void txtAñoKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtAñoKeyPressed
        if(KeyEvent.VK_ENTER == evt.getKeyCode()){
            this.txtJuzgado.requestFocus();
        }
    }//GEN-LAST:event_txtAñoKeyPressed

    private void cboxMesKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_cboxMesKeyPressed
        if(KeyEvent.VK_ENTER == evt.getKeyCode()){
            txtAño.requestFocus();
        }
    }//GEN-LAST:event_cboxMesKeyPressed

    private void txtDiaKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtDiaKeyPressed
        // TODO add your handling code here:
        if(KeyEvent.VK_ENTER == evt.getKeyCode()){
            cboxMes.requestFocus();
        }
    }//GEN-LAST:event_txtDiaKeyPressed

    private void TablaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TablaMouseClicked
        // TODO add your handling code here:
        fila = Tabla.rowAtPoint(evt.getPoint());
        if(fila > -1){
            String provincia = String.valueOf(Tabla.getValueAt(fila, 2));
            String nombre = String.valueOf(Tabla.getValueAt(fila, 1));
            String codigo = String.valueOf(Tabla.getValueAt(fila, 0));
            String fecini = String.valueOf(Tabla.getValueAt(fila, 3));
            String fecfin = String.valueOf(Tabla.getValueAt(fila, 4));
            txtNotario.setText(nombre);
            txtCodNot.setText(codigo);
            txtfecini.setText(fecini);
            txtfecfin.setText(fecfin);
        }
        
        activa();
    }//GEN-LAST:event_TablaMouseClicked

    private void txtBuscaNotarioKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtBuscaNotarioKeyTyped
        // TODO add your handling code here:
        notarios2 nt = new notarios2();
        String[] columNames ={"Codigo","Notario", "Provincia","FechaInicio","FechaFinal"};
        String valor = this.txtBuscaNotario.getText();
        datNot = nt.getDatos(valor);
        DefaultTableModel dat = new DefaultTableModel(datNot,columNames);
        Tabla.setModel(dat);
    }//GEN-LAST:event_txtBuscaNotarioKeyTyped

    private void txtBuscaNotarioKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtBuscaNotarioKeyReleased
        // TODO add your handling code here:
        Tabla.getColumnModel().getColumn(0).setMaxWidth(40);
        Tabla.getColumnModel().getColumn(1).setMaxWidth(500);
        Tabla.getColumnModel().getColumn(2).setMaxWidth(150);
        Tabla.getColumnModel().getColumn(3).setMaxWidth(80);
        Tabla.getColumnModel().getColumn(4).setMaxWidth(80);
    }//GEN-LAST:event_txtBuscaNotarioKeyReleased

    public void actualizar_Tabla(){
            String[] nameColumn =   {"Codigo","Notario", "Provincia","FechaInicio","FechaFinal"};
            String text = "%";
            datNot = nt2.getDatos(text);
            DefaultTableModel datos = new DefaultTableModel(datNot,nameColumn);
            Tabla.setModel(datos);
    }
    
    public void sizeTabla(){
           Tabla.getColumnModel().getColumn(0).setMaxWidth(50);
           Tabla.getColumnModel().getColumn(1).setMaxWidth(500);
           Tabla.getColumnModel().getColumn(2).setMaxWidth(150);
           Tabla.getColumnModel().getColumn(3).setMaxWidth(80);
           Tabla.getColumnModel().getColumn(4).setMaxWidth(80);
    }
    private void txtBuscaNotarioKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtBuscaNotarioKeyPressed
        // TODO add your handling code here:
        actualizar_Tabla();
        sizeTabla();
        try{
            con.conectar();
        }catch(Exception e){
            JOptionPane.showMessageDialog(txtCodNot, e);
        }
    }//GEN-LAST:event_txtBuscaNotarioKeyPressed

    private void txtBuscaNotarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtBuscaNotarioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtBuscaNotarioActionPerformed

    private void txtExpedienteArchivadoKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtExpedienteArchivadoKeyPressed
        if(KeyEvent.VK_ENTER == evt.getKeyCode()){

        }
    }//GEN-LAST:event_txtExpedienteArchivadoKeyPressed

    private void txtSeguidoKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtSeguidoKeyPressed
        if(KeyEvent.VK_ENTER == evt.getKeyCode()){
            txtCausante.requestFocus();
        }
    }//GEN-LAST:event_txtSeguidoKeyPressed

    private void txtFavorecidoKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtFavorecidoKeyPressed
        if(KeyEvent.VK_ENTER == evt.getKeyCode()){
            this.txtSeguido.requestFocus();
        }
    }//GEN-LAST:event_txtFavorecidoKeyPressed

    private void txtOtorganteKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtOtorganteKeyPressed
        if(KeyEvent.VK_ENTER == evt.getKeyCode()){
            txtFavorecido.requestFocus();
        }
    }//GEN-LAST:event_txtOtorganteKeyPressed

    private void txtCausanteKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtCausanteKeyPressed
        // TODO add your handling code here:
        if(KeyEvent.VK_ENTER == evt.getKeyCode()){
            this.txtDia.requestFocus();
        }
    }//GEN-LAST:event_txtCausanteKeyPressed

    private void txtJuzgadoKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtJuzgadoKeyPressed
        // TODO add your handling code here:
        if(KeyEvent.VK_ENTER == evt.getKeyCode()){
            this.txtOtros.requestFocus();
        }
    }//GEN-LAST:event_txtJuzgadoKeyPressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ExpedienteArchivado2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ExpedienteArchivado2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ExpedienteArchivado2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ExpedienteArchivado2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                ExpedienteArchivado2 dialog = new ExpedienteArchivado2(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel LabelIdSol;
    private static javax.swing.JTable Tabla;
    private javax.swing.JButton btnCambiarDatos;
    private javax.swing.JButton btnGuardar;
    private javax.swing.JButton btnImprimir;
    private javax.swing.JButton btnNuevo;
    private javax.swing.JButton btnUsu;
    private javax.swing.JButton btnVisulaizar;
    private javax.swing.JComboBox cboxMes;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel lblCod;
    private javax.swing.JLabel lblIdSol;
    private javax.swing.JLabel lblcodNot;
    private javax.swing.JLabel lblcodigoUsuario;
    private javax.swing.JTextField txtAño;
    private javax.swing.JTextField txtBuscaNotario;
    private javax.swing.JTextField txtCausante;
    private javax.swing.JTextField txtCodNot;
    private javax.swing.JTextField txtDia;
    private javax.swing.JTextField txtExpedienteArchivado;
    private javax.swing.JTextField txtFavorecido;
    private javax.swing.JTextField txtJuzgado;
    private javax.swing.JTextField txtLugar;
    private javax.swing.JTextField txtNom;
    private javax.swing.JTextField txtNotario;
    private javax.swing.JTextField txtNumDoc;
    private javax.swing.JTextField txtOtorgante;
    private javax.swing.JTextArea txtOtros;
    private javax.swing.JTextField txtSeguido;
    private javax.swing.JTextField txtSolicitud;
    private javax.swing.JTextField txtfecfin;
    private javax.swing.JTextField txtfecini;
    // End of variables declaration//GEN-END:variables

  
   
}
