
package sistemasolicitudes;

import java.awt.event.KeyEvent;
import java.sql.*;
import javax.swing.JComboBox;
import javax.swing.JOptionPane;

public final class ExpedienteArchivado extends javax.swing.JDialog {
    conexion con = new conexion();
    int idsol,not;
    String exped, otor, favor, juz, seguido, contra, año, otros, dia,mes, num_solicitud, ver_solicitud, idSol,cod,codigoNotario;
    private ReporteExpArchivado jasper;
    /** Creates new form ExpedienteArchivado */
    public ExpedienteArchivado(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        jasper=new ReporteExpArchivado();

        this.txtSolicitud.setEditable(false);
        this.lblIdSol.setVisible(false);
        this.lblCod.setVisible(false);
        this.jLabel5.setVisible(false);
        this.txtNombreNotario.setVisible(false);
        this.btnCambiarDatos.setVisible(false);
        this.LabelIdSol.setVisible(false);

        try{
            this.dbcbox("select concat(pat_not,' ',mat_not,' ',nom_not) as notario from notarios;",cboxNotario);
        }catch(Exception e){
            System.out.println(e+"mal");
        }
        int solic=0,esc=0;
        try{
                con.conectar();
                ResultSet res=con.consulta("SELECT max(codSol) FROM solicitudes");
                res.next();
                solic=Integer.parseInt(res.getString(1));
                res=con.consulta("SELECT count(idSol) FROM exparchivado");
                res.next();
                esc=Integer.parseInt(res.getString(1));
                con.cierraConexion();
            }catch(SQLException e){
                System.out.println(e);
            }
        txtSolicitud.setText(String.valueOf(solic+1));
        lblIdSol.setText(String.valueOf(esc+1));
    }
    public void dbcbox(String sql,JComboBox a){
            try {
                con.conectar();
                ResultSet rs = con.consulta(sql);
                while(rs.next()){
                    a.addItem (rs.getObject(1));
                }
                con.cierraConexion();
            } catch (SQLException e) {
                System.out.println(e);
            }
        }
    public void desactiva(){
            this.txtSolicitud.setText("");
            this.txtSolicitud.setEditable(false);
            this.txtNumDoc.setEditable(false);
            this.txtNom.setEditable(false);
            this.btnGuardar.setEnabled(false);
            this.btnImprimir.setEnabled(false);
            this.btnUsu.setEnabled(false);
        }
    public void activa(){
            //this.txtSolicitud.setText("");
            this.txtNumDoc.setEditable(true);
            this.txtNom.setEditable(true);
            this.btnGuardar.setEnabled(true);
            //this.btnImprimir.setEnabled(true);
            this.btnUsu.setEnabled(true);
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jPanel5 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        cboxNotario = new javax.swing.JComboBox();
        txtOtor = new javax.swing.JTextField();
        txtFavor = new javax.swing.JTextField();
        txtExped = new javax.swing.JTextField();
        txtJuz = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        txtNombreNotario = new javax.swing.JTextField();
        jPanel6 = new javax.swing.JPanel();
        jLabel16 = new javax.swing.JLabel();
        txtSeguido = new javax.swing.JTextField();
        jLabel17 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        cboxMes = new javax.swing.JComboBox();
        jLabel19 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        txtContra = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtObs = new javax.swing.JTextArea();
        txtAño = new javax.swing.JTextField();
        txtdia = new javax.swing.JTextField();
        btnGuardar = new javax.swing.JButton();
        btnImprimir = new javax.swing.JButton();
        btnNuevo = new javax.swing.JButton();
        jLabel23 = new javax.swing.JLabel();
        txtSolicitud = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        txtNumDoc = new javax.swing.JTextField();
        btnUsu = new javax.swing.JButton();
        txtNom = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        lblCod = new javax.swing.JLabel();
        lblIdSol = new javax.swing.JLabel();
        btnVisulaizar = new javax.swing.JButton();
        btnCambiarDatos = new javax.swing.JButton();
        LabelIdSol = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 22)); // NOI18N
        jLabel1.setText("Expedientes Archivados");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 11, -1, -1));

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)), "Datos del documento", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 12))); // NOI18N

        jPanel5.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel2.setText("Expediente de:");
        jPanel5.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 14, -1, -1));

        jLabel13.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel13.setText("Notario:");
        jPanel5.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 110, -1, -1));

        jLabel14.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel14.setText("Otorgante:");
        jPanel5.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 140, -1, -1));

        jLabel15.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel15.setText("Favorecido:");
        jPanel5.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 170, -1, -1));

        jLabel21.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel21.setText("Juzgado:");
        jPanel5.add(jLabel21, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 200, -1, -1));

        cboxNotario.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        cboxNotario.setModel(new javax.swing.DefaultComboBoxModel(new String[] { " " }));
        cboxNotario.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cboxNotarioItemStateChanged(evt);
            }
        });
        cboxNotario.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                cboxNotarioKeyPressed(evt);
            }
        });
        jPanel5.add(cboxNotario, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 110, 340, -1));

        txtOtor.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        txtOtor.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtOtorKeyPressed(evt);
            }
        });
        jPanel5.add(txtOtor, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 140, 330, -1));

        txtFavor.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        txtFavor.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtFavorKeyPressed(evt);
            }
        });
        jPanel5.add(txtFavor, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 170, 330, -1));

        txtExped.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        txtExped.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtExpedKeyPressed(evt);
            }
        });
        jPanel5.add(txtExped, new org.netbeans.lib.awtextra.AbsoluteConstraints(98, 11, 300, -1));

        txtJuz.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        txtJuz.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtJuzKeyPressed(evt);
            }
        });
        jPanel5.add(txtJuz, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 200, 340, -1));

        jLabel6.setText("Nota:  Presione \" - \" si no hay Notario");
        jPanel5.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 43, -1, -1));

        jLabel7.setText("La lista de Notarios se encuentran en orden alfabetico por Apellido");
        jPanel5.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 60, -1, -1));

        jLabel8.setText("Paterno del Notario");
        jPanel5.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 80, -1, -1));
        jPanel5.add(txtNombreNotario, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 80, 260, -1));

        jLabel16.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel16.setText("Seguido por:");

        txtSeguido.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        txtSeguido.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtSeguidoKeyPressed(evt);
            }
        });

        jLabel17.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel17.setText("En Contra de:");

        jLabel22.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel22.setText("Fecha de Archivamiento:");

        cboxMes.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        cboxMes.setModel(new javax.swing.DefaultComboBoxModel(new String[] { " ", "ENERO", "FEBRERO", "MARZO", "ABRIL", "MAYO", "JUNIO", "JULIO", "AGOSTO", "SETIEMBRE", "OCTUBRE", "NOVIEMBRE", "DICIEMBRE" }));
        cboxMes.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                cboxMesKeyPressed(evt);
            }
        });

        jLabel19.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel19.setText("Mes");

        jLabel18.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel18.setText("Dia");

        jLabel20.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel20.setText("Año");

        txtContra.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        txtContra.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtContraKeyPressed(evt);
            }
        });

        jScrollPane1.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_ALWAYS);

        txtObs.setColumns(20);
        txtObs.setRows(5);
        jScrollPane1.setViewportView(txtObs);

        txtAño.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        txtAño.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtAñoKeyPressed(evt);
            }
        });

        txtdia.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtdiaKeyPressed(evt);
            }
        });

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 383, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel6Layout.createSequentialGroup()
                        .addComponent(jLabel16)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtSeguido, javax.swing.GroupLayout.DEFAULT_SIZE, 309, Short.MAX_VALUE))
                    .addComponent(jLabel22, javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel6Layout.createSequentialGroup()
                        .addComponent(jLabel17)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtContra, javax.swing.GroupLayout.DEFAULT_SIZE, 303, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel6Layout.createSequentialGroup()
                        .addComponent(jLabel18)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtdia, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel19)
                        .addGap(4, 4, 4)
                        .addComponent(cboxMes, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel20)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtAño, javax.swing.GroupLayout.DEFAULT_SIZE, 166, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel16)
                    .addComponent(txtSeguido, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel17)
                    .addComponent(txtContra, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel22)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel18)
                    .addComponent(txtAño, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtdia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel19)
                    .addComponent(cboxMes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel20))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 72, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, 431, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, 223, Short.MAX_VALUE)
                    .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 160, 870, 270));

        btnGuardar.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        btnGuardar.setText("Guardar");
        btnGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGuardarActionPerformed(evt);
            }
        });
        getContentPane().add(btnGuardar, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 440, 130, 40));

        btnImprimir.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        btnImprimir.setText("Imprimir");
        btnImprimir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnImprimirActionPerformed(evt);
            }
        });
        getContentPane().add(btnImprimir, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 440, 130, 40));

        btnNuevo.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        btnNuevo.setText("Nuevo");
        btnNuevo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNuevoActionPerformed(evt);
            }
        });
        getContentPane().add(btnNuevo, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 60, 170, 50));

        jLabel23.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel23.setText("Solicitud N°:");
        getContentPane().add(jLabel23, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 20, -1, -1));

        txtSolicitud.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtSolicitudActionPerformed(evt);
            }
        });
        getContentPane().add(txtSolicitud, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 20, 80, -1));

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel4.setText("N° Documento:");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 57, -1, -1));

        txtNumDoc.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        txtNumDoc.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtNumDocKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtNumDocKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtNumDocKeyTyped(evt);
            }
        });
        getContentPane().add(txtNumDoc, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 58, 179, -1));

        btnUsu.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        btnUsu.setText("BUSCAR SOLICITANTE");
        btnUsu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUsuActionPerformed(evt);
            }
        });
        getContentPane().add(btnUsu, new org.netbeans.lib.awtextra.AbsoluteConstraints(285, 57, -1, -1));

        txtNom.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        txtNom.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtNomKeyPressed(evt);
            }
        });
        getContentPane().add(txtNom, new org.netbeans.lib.awtextra.AbsoluteConstraints(61, 86, 218, -1));

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel3.setText("Nombre:");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 89, -1, -1));

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel5.setText("Codigo Usuario:");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 116, -1, -1));

        lblCod.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        lblCod.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        getContentPane().add(lblCod, new org.netbeans.lib.awtextra.AbsoluteConstraints(104, 113, 81, 18));

        lblIdSol.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        getContentPane().add(lblIdSol, new org.netbeans.lib.awtextra.AbsoluteConstraints(800, 480, 66, 19));

        btnVisulaizar.setText("Visualizar Expediente");
        btnVisulaizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVisulaizarActionPerformed(evt);
            }
        });
        getContentPane().add(btnVisulaizar, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 20, 180, -1));

        btnCambiarDatos.setText("Cambiar Datos");
        btnCambiarDatos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCambiarDatosActionPerformed(evt);
            }
        });
        getContentPane().add(btnCambiarDatos, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 440, 130, 40));

        LabelIdSol.setText("labelIdSol");
        getContentPane().add(LabelIdSol, new org.netbeans.lib.awtextra.AbsoluteConstraints(730, 130, 120, -1));

        jButton1.setText("ReImprimir Solicitud");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 60, 180, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cboxNotarioItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cboxNotarioItemStateChanged

}//GEN-LAST:event_cboxNotarioItemStateChanged

    private void cboxNotarioKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_cboxNotarioKeyPressed
        if(KeyEvent.VK_ENTER == evt.getKeyCode()){
            txtOtor.requestFocus();
        }
}//GEN-LAST:event_cboxNotarioKeyPressed

    private void txtOtorKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtOtorKeyPressed
        if(KeyEvent.VK_ENTER == evt.getKeyCode()){
            txtFavor.requestFocus();
        }
}//GEN-LAST:event_txtOtorKeyPressed

    private void txtFavorKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtFavorKeyPressed
        if(KeyEvent.VK_ENTER == evt.getKeyCode()){
            txtJuz.requestFocus();
        }
}//GEN-LAST:event_txtFavorKeyPressed

    private void txtExpedKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtExpedKeyPressed
        if(KeyEvent.VK_ENTER == evt.getKeyCode()){
            cboxNotario.requestFocus();
        }
}//GEN-LAST:event_txtExpedKeyPressed

    private void txtJuzKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtJuzKeyPressed
        if(KeyEvent.VK_ENTER == evt.getKeyCode()){
            txtSeguido.requestFocus();
        }
}//GEN-LAST:event_txtJuzKeyPressed

    private void txtSeguidoKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtSeguidoKeyPressed
        if(KeyEvent.VK_ENTER == evt.getKeyCode()){
            txtContra.requestFocus();
        }
}//GEN-LAST:event_txtSeguidoKeyPressed

    private void cboxMesKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_cboxMesKeyPressed
        if(KeyEvent.VK_ENTER == evt.getKeyCode()){
            txtAño.requestFocus();
        }
}//GEN-LAST:event_cboxMesKeyPressed

    private void txtContraKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtContraKeyPressed
        if(KeyEvent.VK_ENTER == evt.getKeyCode()){
            txtdia.requestFocus();
        }
}//GEN-LAST:event_txtContraKeyPressed

    private void txtAñoKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtAñoKeyPressed
        if(KeyEvent.VK_ENTER == evt.getKeyCode()){
            txtObs.requestFocus();
        }
}//GEN-LAST:event_txtAñoKeyPressed

    private void txtdiaKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtdiaKeyPressed
        // TODO add your handling code here:
        if(KeyEvent.VK_ENTER == evt.getKeyCode()){
            cboxMes.requestFocus();
        }
}//GEN-LAST:event_txtdiaKeyPressed

    private void btnGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuardarActionPerformed
        cod = lblCod.getText();
        idsol =Integer.parseInt(lblIdSol.getText());
        int codTipSol=5;
        //
        num_solicitud = this.txtSolicitud.getText();
        exped = txtExped.getText().toUpperCase();
        not=Integer.parseInt(String.valueOf(cboxNotario.getSelectedIndex()));
        otor = txtOtor.getText().toUpperCase();
        favor = txtFavor.getText().toUpperCase();
        juz = txtJuz.getText().toUpperCase();
        seguido = txtSeguido.getText().toUpperCase();
        contra = txtContra.getText().toUpperCase();
        dia = this.txtdia.getText().toUpperCase();
        mes = this.cboxMes.getSelectedItem().toString();
        año = txtAño.getText().toUpperCase();
        otros = txtObs.getText().toUpperCase();

        int rpta = JOptionPane.showConfirmDialog(rootPane, "¿Estas seguro de Guardar?","ARP Sistema",JOptionPane.YES_NO_OPTION);
        if(rpta == 0){
        try{
            con.conectar();
            con.insertar("INSERT INTO exparchivado(tipExp,codNot,otorgante,favorecido,juzgado,seguido,contra,dia,mes,anio,obs) "
                    + "VALUES ('"+exped+"','"+not+"','"+otor+"','"+favor+"','"+juz+"','"+seguido+"','"+contra+"','"+dia+"','"+mes+"','"+año+"','"+otros+"');");
            con.insertar("INSERT INTO solicitudes(codSol,codUsu,codTipSol,idSol) VALUES ('"+num_solicitud+"','"+cod+"','"+codTipSol+"','"+idsol+"');");
            con.cierraConexion();
            
            this.btnGuardar.setEnabled(false);
            this.btnImprimir.setEnabled(true);
        }catch(Exception e){
            JOptionPane.showMessageDialog(rootPane, "Error Guardando. " + e);
        }
        }
}//GEN-LAST:event_btnGuardarActionPerformed

    private void btnImprimirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnImprimirActionPerformed
        // TODO add your handling code here:
        String num_sol = txtSolicitud.getText();
        jasper.ejecutarReporte(num_sol);
}//GEN-LAST:event_btnImprimirActionPerformed

    private void btnNuevoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNuevoActionPerformed
        activa();
        this.txtNumDoc.requestFocus();
        int solic=0,esc=0;
        try{
            con.conectar();
            ResultSet res=con.consulta("SELECT max(codSol) FROM solicitudes");
            res.next();
            solic=Integer.parseInt(res.getString(1));
            res=con.consulta("SELECT count(idSol) FROM exparchivado");
            res.next();
            esc=Integer.parseInt(res.getString(1));
            con.cierraConexion();
        }catch(SQLException e){
            System.out.println(e);
        }
        txtSolicitud.setText(String.valueOf(solic+1));
        lblIdSol.setText(String.valueOf(esc+1));
        txtFavor.setText("");
        txtNom.setText("");
        txtNumDoc.setText("");
        txtOtor.setText("");
        txtObs.setText("");
        txtdia.setText("");
        cboxMes.setSelectedIndex(0);
        txtAño.setText("");
        txtExped.setText("");
        cboxNotario.setSelectedIndex(0);
        txtJuz.setText("");
        txtSeguido.setText("");
        txtContra.setText("");
        this.txtObs.setText("");
}//GEN-LAST:event_btnNuevoActionPerformed

    private void txtNumDocKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtNumDocKeyPressed
        if(KeyEvent.VK_ENTER == evt.getKeyCode()){
            btnUsu.doClick();
        }
}//GEN-LAST:event_txtNumDocKeyPressed

    private void txtNumDocKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtNumDocKeyReleased
        if(txtNumDoc.getText().length()>10){
            btnUsu.doClick();
        }
}//GEN-LAST:event_txtNumDocKeyReleased

    private void txtNumDocKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtNumDocKeyTyped
        int n = (int)evt.getKeyChar();
        if(n>=48 && n<=57 || n==13 || n==127){

        }else{
            evt.setKeyChar((char)KeyEvent.VK_CLEAR);
        }
}//GEN-LAST:event_txtNumDocKeyTyped

    private void btnUsuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUsuActionPerformed
        int numero = txtNumDoc.getText().length();
        String dni2 = null;
        
        if (numero <8){
            JOptionPane.showMessageDialog(rootPane, "Numero de Digitos de DNI Menor que 8 Numeros y de RUC es 11");
            this.txtNumDoc.requestFocus();
        }else{
            if (numero==8)
            {
            String dni=this.txtNumDoc.getText();
            try{
                con.conectar();
               
               
                ResultSet rs=con.consulta("SELECT codUsu,CONCAT(nombre,' ',apePat,' ',apeMat) AS nombre FROM usuarios WHERE numDoc='"+dni+"' LIMIT 0,1;");
                rs.next();
                this.txtNom.setText(rs.getString(2));
                this.lblCod.setText(rs.getString(1));
                con.cierraConexion();
            }catch(SQLException e){
                JOptionPane.showMessageDialog(rootPane, "Usuario no encontrado","Administrador de Sistema",JOptionPane.INFORMATION_MESSAGE);
                dni2 = this.txtNumDoc.getText();
                dialogNuevoUsuario p=new dialogNuevoUsuario(null,false,dni2);
                p.setVisible(true);
            }
            

        }else {if (numero==11){
            String ruc=this.txtNumDoc.getText();
            try{
                con.conectar();
                ResultSet rs=con.consulta("SELECT codUsu, apeMat from usuarios where numDoc='"+ruc+"' LIMIT 0,1;");
                rs.next();
                this.txtNom.setText(rs.getString(2));
                this.lblCod.setText(rs.getString(1));
                con.cierraConexion();
            }catch(SQLException e){
                JOptionPane.showMessageDialog(rootPane, "Empresa no registrada","Administrador del Sitema", JOptionPane.INFORMATION_MESSAGE);
                // = this.txtNunDNI.getText();
                dialogNuevoJuridico p=new dialogNuevoJuridico(null, false, ruc);
                p.setVisible(true);
            }
        }}
        }
}//GEN-LAST:event_btnUsuActionPerformed

    private void txtNomKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtNomKeyPressed
        if(KeyEvent.VK_ENTER == evt.getKeyCode()){
            txtExped.requestFocus();
        }
}//GEN-LAST:event_txtNomKeyPressed

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        // TODO add your handling code here:
        desactiva();
    }//GEN-LAST:event_formWindowOpened

    private void btnVisulaizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVisulaizarActionPerformed
        // TODO add your handling code here:
        ver_solicitud = JOptionPane.showInputDialog("Ingrese Numero de Solicitud a visualizar");

        this.txtNumDoc.setEditable(true);
        this.btnUsu.setEnabled(true);
        this.txtNombreNotario.setVisible(true);
        this.btnGuardar.setVisible(false);
        this.btnCambiarDatos.setVisible(true);

        try{
            con.conectar();
            ResultSet res = con.consulta("SELECT s.codSol, s.idSol, CONCAT(u.nombre,' ', u.apePat,' ',u.apeMat) AS usuario,u.codUsu, u.codDis, u.numDoc, u.direccion, ea.tipExp, CONCAT(n.nom_not,' ',n.pat_not,' ',n.mat_not) AS notario, ea.otorgante, ea.favorecido, ea.juzgado, ea.seguido,ea.contra,ea.dia, ea.mes, ea.anio, ea.obs FROM solicitudes AS s, usuarios AS u,exparchivado AS ea, notarios AS n WHERE s.idSol = ea.idSol AND s.codUsu = u.codUsu AND ea.codNot=n.cod_not AND s.codSol ="+ver_solicitud+";");
            res.next();
            this.txtSolicitud.setText(res.getString("codSol").toString());
            this.txtNumDoc.setText(res.getString("numDoc").toString());
            this.txtNom.setText(res.getString("usuario"));
            this.txtExped.setText(res.getString("tipExp"));
            this.txtNombreNotario.setText(res.getString("notario"));
            this.txtOtor.setText(res.getString("otorgante"));
            this.txtFavor.setText(res.getString("favorecido"));
            this.txtJuz.setText(res.getString("juzgado"));
            this.txtSeguido.setText(res.getString("seguido"));
            this.txtContra.setText(res.getString("contra"));
            this.txtdia.setText(res.getString("dia"));
            this.cboxMes.setSelectedItem(res.getString("mes"));
            this.txtAño.setText(res.getString("anio"));
            this.txtObs.setText(res.getString("obs"));
            this.LabelIdSol.setText(res.getString("idSol"));
            this.lblCod.setText(res.getString("codUsu"));
        }catch(Exception e){
            JOptionPane.showMessageDialog(rootPane, e);
        }
    }//GEN-LAST:event_btnVisulaizarActionPerformed

    private void btnCambiarDatosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCambiarDatosActionPerformed
        // TODO add your handling code here:
        cod = this.lblCod.getText();
        idsol =Integer.parseInt(lblIdSol.getText());

        num_solicitud = this.txtSolicitud.getText();
        idSol = this.LabelIdSol.getText();
        exped = txtExped.getText().toUpperCase();
        not=Integer.parseInt(String.valueOf(cboxNotario.getSelectedIndex()));
        otor = txtOtor.getText().toUpperCase();
        favor = txtFavor.getText().toUpperCase();
        juz = this.txtJuz.getText().toUpperCase();
        seguido = txtSeguido.getText().toUpperCase();
        contra = txtContra.getText().toUpperCase();
        dia = this.txtdia.getText().toUpperCase();
        mes = this.cboxMes.getSelectedItem().toString();
        año = txtAño.getText().toUpperCase();
        otros = txtObs.getText().toUpperCase();
        if(not==0){
            codigoNotario = "113";
        }
        
        int rpta1 = JOptionPane.showConfirmDialog(rootPane,"¿Esta seguro de realizar estos cambios?","ARP Sistema",JOptionPane.YES_NO_OPTION);
        if(rpta1 == 0){
            try{
                con.conectar();
                con.actualizar("UPDATE `recepcion`.`exparchivado` SET `tipExp`='"+exped+"', `codNot`='"+codigoNotario+"', `otorgante`='"+otor+"', `favorecido`='"+favor+"', `juzgado`='"+juz+"', `seguido`='"+seguido+"', `contra`='"+contra+"', `dia`='"+dia+"', `mes`='"+mes+"', `anio`='"+año+"', `obs`='"+otros+"' WHERE `idSol`='"+idSol+"';");
                con.actualizar("UPDATE solicitudes SET codUsu = '"+cod+"', idSol = '"+idSol+"' WHERE codSol = '"+num_solicitud+"';");
                JOptionPane.showMessageDialog(rootPane, "Datos Modificados Satisfactotiamente");
                //con.cierraConexion();

            }catch(Exception e){
                JOptionPane.showMessageDialog(rootPane, "Error Cambiando datos. " + e);
            }
        }
        this.btnCambiarDatos.setVisible(false);
        this.btnGuardar.setEnabled(false);
        this.btnImprimir.setEnabled(true);
    }//GEN-LAST:event_btnCambiarDatosActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        String solicitudD = JOptionPane.showInputDialog("Escriba el Numero de Solicitud");
        String num_sol = solicitudD;
        jasper.ejecutarReporte(num_sol);
}//GEN-LAST:event_jButton1ActionPerformed

    private void txtSolicitudActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtSolicitudActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtSolicitudActionPerformed

    /**
    * @param args the command line arguments
    */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                ExpedienteArchivado dialog = new ExpedienteArchivado(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel LabelIdSol;
    private javax.swing.JButton btnCambiarDatos;
    private javax.swing.JButton btnGuardar;
    private javax.swing.JButton btnImprimir;
    private javax.swing.JButton btnNuevo;
    private javax.swing.JButton btnUsu;
    private javax.swing.JButton btnVisulaizar;
    private javax.swing.JComboBox cboxMes;
    private javax.swing.JComboBox cboxNotario;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblCod;
    private javax.swing.JLabel lblIdSol;
    private javax.swing.JTextField txtAño;
    private javax.swing.JTextField txtContra;
    private javax.swing.JTextField txtExped;
    private javax.swing.JTextField txtFavor;
    private javax.swing.JTextField txtJuz;
    private javax.swing.JTextField txtNom;
    private javax.swing.JTextField txtNombreNotario;
    private javax.swing.JTextField txtNumDoc;
    private javax.swing.JTextArea txtObs;
    private javax.swing.JTextField txtOtor;
    private javax.swing.JTextField txtSeguido;
    private javax.swing.JTextField txtSolicitud;
    private javax.swing.JTextField txtdia;
    // End of variables declaration//GEN-END:variables

}
