
package sistemasolicitudes;

import java.awt.event.KeyEvent;
import java.sql.*;
import javax.swing.JComboBox;
import javax.swing.JOptionPane;

public final class ProNoContencioso extends javax.swing.JDialog {
    conexion con = new conexion();
    int cod,idsol,not, notario;
    //
    String proc, seguido, contra, causante, lugar, año, otros, num_solicitud, dia, mes, ver_solicitud, codUsu;
    private ReporteProcNoContencioso jasper;
    /** Creates new form ProNoContencioso */
    public ProNoContencioso(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();

        jasper=new ReporteProcNoContencioso();
        txtSolicitud.setEditable(false);
        lblIdSol.setVisible(false);
        lblCod.setVisible(false);
        jLabel5.setVisible(false);
        LabelIdSol.setVisible(false);
        //
        try{
            this.dbcbox("SELECT CONCAT(pat_not,' ',mat_not,' ',nom_not) AS notario FROM notarios;",cboxNotario);
        }catch(Exception e){
            System.out.println(e+"mal");
        }
        //
        int solic=0,esc=0;
        try{
                con.conectar();
                ResultSet res=con.consulta("SELECT COUNT(codSol) FROM solicitudes;");
                res.next();
                solic=Integer.parseInt(res.getString(1));
                res=con.consulta("SELECT COUNT(idSol) FROM procontenciosos;");
                res.next();
                esc=Integer.parseInt(res.getString(1));
                con.cierraConexion();
            }catch(SQLException e){
                System.out.println(e);
            }
        txtSolicitud.setText(String.valueOf(solic+1));
        lblIdSol.setText(String.valueOf(esc+1));
    }
    public void dbcbox(String sql,JComboBox a){
            try {
                con.conectar();
                ResultSet rs = con.consulta(sql);
                while(rs.next()){
                    a.addItem (rs.getObject(1));
                }
                rs.close();
            } catch (SQLException e) {
                 System.out.println(e);
            }
        }
    public void desactiva(){
            this.txtSolicitud.setText("");
            this.txtSolicitud.setEditable(false);
            this.txtNumDoc.setEditable(false);
            this.txtNom.setEditable(false);
            this.btnGuardar.setEnabled(false);
            this.btnImprimir.setEnabled(false);
            this.btnUsu.setEnabled(false);
        }
    public void activa(){
            //this.txtSolicitud.setText("");
            this.txtNumDoc.setEditable(true);
            this.txtNom.setEditable(true);
            this.btnGuardar.setEnabled(true);
            //this.btnImprimir.setEnabled(true);
            this.btnUsu.setEnabled(true);
    }
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel5 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        lblIdSol = new javax.swing.JLabel();
        lblCod = new javax.swing.JLabel();
        btnNuevo = new javax.swing.JButton();
        btnImprimir = new javax.swing.JButton();
        btnGuardar = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jPanel5 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        txtSeguido = new javax.swing.JTextField();
        txtContra = new javax.swing.JTextField();
        txtCausante = new javax.swing.JTextField();
        cboxNotario = new javax.swing.JComboBox();
        txtPro = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jPanel6 = new javax.swing.JPanel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        cboxMes = new javax.swing.JComboBox();
        jLabel19 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        txtLugar = new javax.swing.JTextField();
        txtAño = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtOtros = new javax.swing.JTextArea();
        txtdia = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        btnUsu = new javax.swing.JButton();
        txtNom = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        txtNumDoc = new javax.swing.JTextField();
        jLabel23 = new javax.swing.JLabel();
        txtSolicitud = new javax.swing.JTextField();
        btnVisulaizar = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        LabelIdSol = new javax.swing.JLabel();
        btnCambiarDatos = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel5.setText("Codigo Usuario:");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 116, -1, -1));

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel3.setText("Nombre:");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 90, -1, -1));

        lblIdSol.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        getContentPane().add(lblIdSol, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 120, 58, 19));

        lblCod.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        lblCod.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        getContentPane().add(lblCod, new org.netbeans.lib.awtextra.AbsoluteConstraints(104, 113, 81, 18));

        btnNuevo.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        btnNuevo.setText("Nuevo");
        btnNuevo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNuevoActionPerformed(evt);
            }
        });
        getContentPane().add(btnNuevo, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 50, 130, 60));

        btnImprimir.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        btnImprimir.setText("Imprimir");
        btnImprimir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnImprimirActionPerformed(evt);
            }
        });
        getContentPane().add(btnImprimir, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 380, 130, 40));

        btnGuardar.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        btnGuardar.setText("Guardar");
        btnGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGuardarActionPerformed(evt);
            }
        });
        getContentPane().add(btnGuardar, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 380, 130, 40));

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)), "Datos del documento", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 12))); // NOI18N
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel5.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel2.setText("Proceso de:");
        jPanel5.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 14, -1, -1));

        jLabel13.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel13.setText("Seguido por:");
        jPanel5.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 41, -1, -1));

        jLabel14.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel14.setText("En contra de:");
        jPanel5.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 68, -1, -1));

        jLabel15.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel15.setText("Causante:");
        jPanel5.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 95, -1, -1));

        jLabel21.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel21.setText("Notario:");
        jPanel5.add(jLabel21, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 142, -1, -1));

        txtSeguido.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        txtSeguido.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtSeguidoKeyPressed(evt);
            }
        });
        jPanel5.add(txtSeguido, new org.netbeans.lib.awtextra.AbsoluteConstraints(84, 38, 306, -1));

        txtContra.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        txtContra.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtContraKeyPressed(evt);
            }
        });
        jPanel5.add(txtContra, new org.netbeans.lib.awtextra.AbsoluteConstraints(89, 65, 301, -1));

        txtCausante.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        txtCausante.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtCausanteKeyPressed(evt);
            }
        });
        jPanel5.add(txtCausante, new org.netbeans.lib.awtextra.AbsoluteConstraints(68, 92, 322, -1));

        cboxNotario.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        cboxNotario.setModel(new javax.swing.DefaultComboBoxModel(new String[] { " " }));
        cboxNotario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cboxNotarioActionPerformed(evt);
            }
        });
        cboxNotario.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                cboxNotarioKeyPressed(evt);
            }
        });
        jPanel5.add(cboxNotario, new org.netbeans.lib.awtextra.AbsoluteConstraints(57, 139, 333, -1));

        txtPro.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        txtPro.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtProKeyPressed(evt);
            }
        });
        jPanel5.add(txtPro, new org.netbeans.lib.awtextra.AbsoluteConstraints(79, 11, 311, -1));

        jLabel6.setText("Escribe \" - \" sin Notario. Ordenado por Apellido Paterno");
        jPanel5.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 119, -1, -1));

        jPanel2.add(jPanel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(15, 31, 400, 180));

        jLabel16.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel16.setText("Lugar:");

        jLabel17.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel17.setText("Fecha del Proceso:");

        cboxMes.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        cboxMes.setModel(new javax.swing.DefaultComboBoxModel(new String[] { " ", "ENERO", "FEBRERO", "MARZO", "ABRIL", "MAYO", "JUNIO", "JULIO", "AGOSTO", "SETIEMBRE", "OCTUBRE", "NOVIEMBRE", "DICIEMBRE" }));
        cboxMes.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                cboxMesKeyPressed(evt);
            }
        });

        jLabel19.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel19.setText("Mes");

        jLabel18.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel18.setText("Dia");

        jLabel20.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel20.setText("Año");

        txtLugar.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        txtLugar.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtLugarKeyPressed(evt);
            }
        });

        txtAño.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        txtAño.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtAñoKeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtAñoKeyTyped(evt);
            }
        });

        jScrollPane1.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_ALWAYS);

        txtOtros.setColumns(20);
        txtOtros.setRows(5);
        jScrollPane1.setViewportView(txtOtros);

        txtdia.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtdiaKeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtdiaKeyTyped(evt);
            }
        });

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 350, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel6Layout.createSequentialGroup()
                        .addComponent(jLabel16)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtLugar, javax.swing.GroupLayout.DEFAULT_SIZE, 312, Short.MAX_VALUE))
                    .addComponent(jLabel17, javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel6Layout.createSequentialGroup()
                        .addComponent(jLabel18)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtdia, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel19)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cboxMes, 0, 154, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel20)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtAño, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel16)
                    .addComponent(txtLugar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel17)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel18)
                    .addComponent(cboxMes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtAño, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtdia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel19)
                    .addComponent(jLabel20))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 74, Short.MAX_VALUE))
        );

        jPanel2.add(jPanel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 30, 370, 160));

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 144, 890, 220));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 22)); // NOI18N
        jLabel1.setText("Procesos no Contenciosos");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 11, -1, -1));

        btnUsu.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        btnUsu.setText("BUSCAR SOLICITANTE");
        btnUsu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUsuActionPerformed(evt);
            }
        });
        getContentPane().add(btnUsu, new org.netbeans.lib.awtextra.AbsoluteConstraints(316, 57, -1, -1));

        txtNom.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        txtNom.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtNomKeyPressed(evt);
            }
        });
        getContentPane().add(txtNom, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 90, 440, -1));

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel4.setText("N° Documento:");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 57, -1, -1));

        txtNumDoc.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        txtNumDoc.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtNumDocKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtNumDocKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtNumDocKeyTyped(evt);
            }
        });
        getContentPane().add(txtNumDoc, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 58, 206, -1));

        jLabel23.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel23.setText("Solicitud N°:");
        getContentPane().add(jLabel23, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 20, 70, -1));
        getContentPane().add(txtSolicitud, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 20, 80, -1));

        btnVisulaizar.setText("Visualizar Proceso");
        btnVisulaizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVisulaizarActionPerformed(evt);
            }
        });
        getContentPane().add(btnVisulaizar, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 50, 180, -1));

        jButton1.setText("ReImprimir Solicitud");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 90, 180, -1));

        LabelIdSol.setText("LabelIdSol");
        getContentPane().add(LabelIdSol, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 130, -1, -1));

        btnCambiarDatos.setText("Cambiar Datos");
        btnCambiarDatos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCambiarDatosActionPerformed(evt);
            }
        });
        getContentPane().add(btnCambiarDatos, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 380, 130, 40));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnNuevoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNuevoActionPerformed
        activa();
        txtNumDoc.requestFocus();
        int solic=0,esc=0;
        try{
            con.conectar();
            ResultSet res=con.consulta("SELECT MAX(codSol) FROM solicitudes;");
            res.next();
            solic=Integer.parseInt(res.getString(1));
            res=con.consulta("SELECT COUNT(idSol) FROM procontenciosos;");
            res.next();
            esc=Integer.parseInt(res.getString(1));
            con.cierraConexion();
        }catch(SQLException e){
            System.out.println(e);
        }
        txtSolicitud.setText(String.valueOf(solic+1));
        lblIdSol.setText(String.valueOf(esc+1));
        txtNom.setText("");
        txtNumDoc.setText("");;
        txtOtros.setText("");
        this.txtdia.getText();
        cboxMes.setSelectedIndex(0);
        txtAño.setText("");
        txtPro.setText("");
        txtSeguido.setText("");
        txtContra.setText("");
        txtCausante.setText("");
        cboxNotario.setSelectedIndex(0);
        txtLugar.setText("");
}//GEN-LAST:event_btnNuevoActionPerformed

    private void btnImprimirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnImprimirActionPerformed
        // TODO add your handling code here:
        String num_sol = txtSolicitud.getText();
        jasper.ejecutarReporte(num_sol);
}//GEN-LAST:event_btnImprimirActionPerformed

    private void btnGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuardarActionPerformed
        cod = Integer.parseInt(lblCod.getText());
        idsol =Integer.parseInt(lblIdSol.getText());
        int codTipSol=6;
        //
        num_solicitud = this.txtSolicitud.getText();
        proc = txtPro.getText().toUpperCase();
        not = this.cboxNotario.getSelectedIndex();
        seguido = txtSeguido.getText().toUpperCase();
        contra = txtContra.getText().toUpperCase();
        causante = txtCausante.getText().toUpperCase();
        lugar = txtLugar.getText().toUpperCase();
        dia = this.txtdia.getText();
        mes = this.cboxMes.getSelectedItem().toString();
        año = txtAño.getText();
        otros = txtOtros.getText().toUpperCase();

        if(not ==0){
            JOptionPane.showMessageDialog(rootPane, "Debe Seleccionar Notario.  Si no hay Notario presione el Signo Menos\"-\" para Ninguno.");
        }else{
            int rpta = JOptionPane.showConfirmDialog(rootPane, "¿Estas seguro de Guardar?","ARP Sistema",JOptionPane.YES_NO_OPTION);
            if(rpta == 0){
            try{
                con.conectar();
                con.insertar("INSERT INTO procontenciosos(tipPro,seguido,contra,causante,codNot,lugar,dia,mes,anio,obs) "
                        + "VALUES ('"+proc+"','"+seguido+"','"+contra+"','"+causante+"','"+not+"','"+lugar+"','"+dia+"','"+mes+"','"+año+"','"+otros+"');");
                con.insertar("INSERT INTO solicitudes(codSol,codUsu,codTipSol,idSol) VALUES ('"+num_solicitud+"','"+cod+"','"+codTipSol+"','"+idsol+"');");
                con.cierraConexion();
            
                this.btnGuardar.setEnabled(false);
                this.btnImprimir.setEnabled(true);
            }catch(Exception e){
                JOptionPane.showMessageDialog(rootPane, e);
            }
            }
        }
    }//GEN-LAST:event_btnGuardarActionPerformed

    private void txtSeguidoKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtSeguidoKeyPressed
        if(KeyEvent.VK_ENTER == evt.getKeyCode()){
            txtContra.requestFocus();
        }
}//GEN-LAST:event_txtSeguidoKeyPressed

    private void txtContraKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtContraKeyPressed
        if(KeyEvent.VK_ENTER == evt.getKeyCode()){
            txtCausante.requestFocus();
        }
}//GEN-LAST:event_txtContraKeyPressed

    private void txtCausanteKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtCausanteKeyPressed
        if(KeyEvent.VK_ENTER == evt.getKeyCode()){
            cboxNotario.requestFocus();
        }
}//GEN-LAST:event_txtCausanteKeyPressed

    private void cboxNotarioKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_cboxNotarioKeyPressed
        if(KeyEvent.VK_ENTER == evt.getKeyCode()){
            txtLugar.requestFocus();
        }
}//GEN-LAST:event_cboxNotarioKeyPressed

    private void txtProKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtProKeyPressed
        if(KeyEvent.VK_ENTER == evt.getKeyCode()){
            txtSeguido.requestFocus();
        }
}//GEN-LAST:event_txtProKeyPressed

    private void cboxMesKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_cboxMesKeyPressed
        if(KeyEvent.VK_ENTER == evt.getKeyCode()){
            txtAño.requestFocus();
        }
}//GEN-LAST:event_cboxMesKeyPressed

    private void txtLugarKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtLugarKeyPressed
        if(KeyEvent.VK_ENTER == evt.getKeyCode()){
            txtdia.requestFocus();
        }
}//GEN-LAST:event_txtLugarKeyPressed

    private void txtAñoKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtAñoKeyPressed
        if(KeyEvent.VK_ENTER == evt.getKeyCode()){
            txtOtros.requestFocus();
        }
}//GEN-LAST:event_txtAñoKeyPressed

    private void txtAñoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtAñoKeyTyped
        // TODO add your handling code here:
        int n = (int)evt.getKeyChar();
        if(n>=48 && n<=57 || n==13 || n==127){
        }else{
            evt.setKeyChar((char)KeyEvent.VK_CLEAR);
        }
}//GEN-LAST:event_txtAñoKeyTyped

    private void txtdiaKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtdiaKeyPressed
        // TODO add your handling code here:
        if(KeyEvent.VK_ENTER == evt.getKeyCode()){
            cboxMes.requestFocus();
        }
}//GEN-LAST:event_txtdiaKeyPressed

    private void txtdiaKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtdiaKeyTyped
        // TODO add your handling code here:
        int n = (int)evt.getKeyChar();
        if(n>=48 && n<=57 || n==13 || n==127){
        }else{
            evt.setKeyChar((char)KeyEvent.VK_CLEAR);
        }
}//GEN-LAST:event_txtdiaKeyTyped

    private void btnUsuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUsuActionPerformed
        int numero = txtNumDoc.getText().length();
        String dni2 = null;
        
        if (numero <8){
            JOptionPane.showMessageDialog(rootPane, "Numero de Digitos de DNI Menor que 8 Numeros y de RUC es 11");
            this.txtNumDoc.requestFocus();
        }else{
            if (numero==8)
            {
            String dni=this.txtNumDoc.getText();
            try{
                con.conectar();
               
               
                ResultSet rs=con.consulta("SELECT codUsu,CONCAT(nombre,' ',apePat,' ',apeMat) AS nombre FROM usuarios WHERE numDoc='"+dni+"' LIMIT 0,1;");
                rs.next();
                this.txtNom.setText(rs.getString(2));
                this.lblCod.setText(rs.getString(1));
                con.cierraConexion();
            }catch(SQLException e){
                JOptionPane.showMessageDialog(rootPane, "Usuario no encontrado","Administrador de Sistema",JOptionPane.INFORMATION_MESSAGE);
                dni2 = this.txtNumDoc.getText();
                dialogNuevoUsuario p=new dialogNuevoUsuario(null,true,dni2);
                p.setVisible(true);
            }
            

        }else {if (numero==11){
            String ruc=this.txtNumDoc.getText();
            try{
                con.conectar();
                ResultSet rs=con.consulta("SELECT codUsu, apeMat from usuarios where numDoc='"+ruc+"' LIMIT 0,1;");
                rs.next();
                this.txtNom.setText(rs.getString(2));
                this.lblCod.setText(rs.getString(1));
                con.cierraConexion();
            }catch(SQLException e){
                JOptionPane.showMessageDialog(rootPane, "Empresa no registrada","Administrador del Sitema", JOptionPane.INFORMATION_MESSAGE);
                // = this.txtNunDNI.getText();
                dialogNuevoJuridico p=new dialogNuevoJuridico(null, true, ruc);
                p.setVisible(true);
            }
        }}
        }
}//GEN-LAST:event_btnUsuActionPerformed

    private void txtNomKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtNomKeyPressed
        if(KeyEvent.VK_ENTER == evt.getKeyCode()){
            txtPro.requestFocus();
        }
}//GEN-LAST:event_txtNomKeyPressed

    private void txtNumDocKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtNumDocKeyPressed
        if(KeyEvent.VK_ENTER == evt.getKeyCode()){
            btnUsu.doClick();
        }
}//GEN-LAST:event_txtNumDocKeyPressed

    private void txtNumDocKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtNumDocKeyReleased
        if(txtNumDoc.getText().length()>7){
            btnUsu.doClick();
        }
}//GEN-LAST:event_txtNumDocKeyReleased

    private void txtNumDocKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtNumDocKeyTyped
        int n = (int)evt.getKeyChar();
        if(n>=48 && n<=57 || n==13 || n==127){
        }else{
            evt.setKeyChar((char)KeyEvent.VK_CLEAR);
        }
}//GEN-LAST:event_txtNumDocKeyTyped

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        // TODO add your handling code here:
        desactiva();
    }//GEN-LAST:event_formWindowOpened

    private void btnVisulaizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVisulaizarActionPerformed
        // TODO add your handling code here:
        ver_solicitud = JOptionPane.showInputDialog("Ingrese Numero de Solicitud a visualizar");

        this.txtNumDoc.setEditable(true);
        this.btnUsu.setEnabled(true);

        this.btnGuardar.setVisible(false);
        this.btnCambiarDatos.setVisible(true);

        try{
            con.conectar();
            ResultSet res = con.consulta("SELECT s.codSol,s.idSol, CONCAT(u.nombre,' ',u.apePat,' ',u.apeMat)as usuario,u.codUsu, u.codDis,u.numDoc, u.direccion,pc.tipPro,pc.seguido,pc.contra,pc.causante,CONCAT(n.nom_not,' ',n.pat_not,' ',n.mat_not) as notario,pc.lugar,pc.dia,pc.mes,pc.anio,pc.obs FROM solicitudes AS s, usuarios AS u, procontenciosos as pc, notarios as n WHERE s.codUsu = u.codUsu  and s.idSol=pc.idSol and pc.codNot=n.cod_not and s.codSol ="+ver_solicitud+";");
            res.next();
            this.txtSolicitud.setText(res.getString("codSol").toString());
            this.txtNumDoc.setText(res.getString("numDoc").toString());
            this.txtNom.setText(res.getString("usuario"));

            this.txtPro.setText(res.getString("tipPro"));
            this.txtSeguido.setText(res.getString("seguido"));
            this.txtContra.setText(res.getString("contra"));
            this.txtCausante.setText(res.getString("causante"));
            this.cboxNotario.setSelectedItem(res.getString("notario"));
            this.txtLugar.setText(res.getString("lugar"));
            this.txtdia.setText(res.getString("dia"));
            this.cboxMes.setSelectedItem(res.getString("mes"));
            this.txtAño.setText(res.getString("anio"));
            this.txtOtros.setText(res.getString("obs"));
            this.LabelIdSol.setText(res.getString("idSol"));
            this.lblCod.setText(res.getString("codUsu"));
        }catch(Exception e){
            JOptionPane.showMessageDialog(rootPane, e);
        }
}//GEN-LAST:event_btnVisulaizarActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        String solicitudD = JOptionPane.showInputDialog("Escriba el Numero de Solicitud");
        String num_sol = solicitudD;
        jasper.ejecutarReporte(num_sol);
}//GEN-LAST:event_jButton1ActionPerformed

    private void btnCambiarDatosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCambiarDatosActionPerformed
        // TODO add your handling code here:
        codUsu = this.lblCod.getText();   //Codigo del usuario
        idsol =Integer.parseInt(this.LabelIdSol.getText());   //

        num_solicitud = this.txtSolicitud.getText();

        proc=this.txtPro.getText().toUpperCase();
        seguido=this.txtSeguido.getText().toUpperCase();
        contra=this.txtContra.getText().toUpperCase();
        causante = this.txtCausante.getText().toUpperCase();
        not=this.cboxNotario.getSelectedIndex();
        lugar = this.txtLugar.getText().toUpperCase();
        dia = this.txtdia.getText().toUpperCase();
        mes = this.cboxMes.getSelectedItem().toString();
        año = txtAño.getText().toUpperCase();
        otros = txtOtros.getText().toUpperCase();

        if(not == 0){
            JOptionPane.showMessageDialog(rootPane, "Debe Seleccionar un Notario. Si no hay Notario, presione el signo menos \"-\", para seleccionar ninguno.\nConsulte con el Adminsitrador del sistema.");
        }
        else{
        int rpta1 = JOptionPane.showConfirmDialog(rootPane,"¿Esta seguro de realizar estos cambios?","ARP Sistema",JOptionPane.YES_NO_OPTION);
        if(rpta1 == 0){
            try{
                con.conectar();
                con.actualizar("UPDATE procontenciosos SET `tipPro`='"+proc+"', `seguido`='"+seguido+"', `contra`='"+contra+"', `causante`='"+causante+"', `codNot`='"+not+"', `lugar`='"+lugar+"', `dia`='"+dia+"', `mes`='"+mes+"', `anio`='"+año+"', `obs`='"+otros+"' WHERE `idSol`='"+idsol+"';");
                con.actualizar("UPDATE solicitudes SET codUsu = '"+codUsu+"', idSol = '"+idsol+"' WHERE codSol = '"+num_solicitud+"';");
                JOptionPane.showMessageDialog(rootPane, "Datos Modificados Satisfactotiamente");
                //con.cierraConexion();
            }catch(Exception e){
                JOptionPane.showMessageDialog(rootPane, "Error Cambiando datos. " + e);
            }
        }
        
        this.btnCambiarDatos.setVisible(false);
        this.btnGuardar.setEnabled(false);
        this.btnImprimir.setEnabled(true);
        }
}//GEN-LAST:event_btnCambiarDatosActionPerformed

    private void cboxNotarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cboxNotarioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cboxNotarioActionPerformed

    /**
    * @param args the command line arguments
    */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                ProNoContencioso dialog = new ProNoContencioso(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel LabelIdSol;
    private javax.swing.JButton btnCambiarDatos;
    private javax.swing.JButton btnGuardar;
    private javax.swing.JButton btnImprimir;
    private javax.swing.JButton btnNuevo;
    private javax.swing.JButton btnUsu;
    private javax.swing.JButton btnVisulaizar;
    private javax.swing.JComboBox cboxMes;
    private javax.swing.JComboBox cboxNotario;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblCod;
    private javax.swing.JLabel lblIdSol;
    private javax.swing.JTextField txtAño;
    private javax.swing.JTextField txtCausante;
    private javax.swing.JTextField txtContra;
    private javax.swing.JTextField txtLugar;
    private javax.swing.JTextField txtNom;
    private javax.swing.JTextField txtNumDoc;
    private javax.swing.JTextArea txtOtros;
    private javax.swing.JTextField txtPro;
    private javax.swing.JTextField txtSeguido;
    private javax.swing.JTextField txtSolicitud;
    private javax.swing.JTextField txtdia;
    // End of variables declaration//GEN-END:variables

}
